import { communityForPublicCell, neighbourhoodForPublicCell } from '@animalhelper/domain';
import { useRouter } from 'expo-router';
import { useEffect,useState } from 'react';
import { Pressable,StyleSheet,Text,View } from 'react-native';
import { getSupabaseClient } from '../api/supabase';
import { readSessionSubjectStrict,subscribeSessionSubject } from '../auth/session-subject';
import { AppIcon } from '../components/AppIcon';
import { useNativeColors } from '../design/native-colors';
import { communityLabel } from './singapore-communities';
import type { Locale } from '../i18n/catalog';
type Activity={community:string;communityId:string;place:string|null;time:string};
export function CatCommunityContext({animalId,locale}:{animalId:string;locale:Locale}){
 const c=useNativeColors(),router=useRouter(),cn=locale==='zh-CN';const [activities,setActivities]=useState<Activity[]>([]);const [failed,setFailed]=useState(false);const [revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;let generation=0;const load=async()=>{const ticket=++generation;setActivities([]);setFailed(false);try{const owner=await readSessionSubjectStrict();const client=getSupabaseClient();if(!client)throw new Error('unavailable');const {data,error}=await client.rpc('list_public_cat_community_activity',{p_animal_id:animalId});if(error||!Array.isArray(data)||data.length>10)throw new Error('unavailable');const safe:Activity[]=[];for(const row of data){if(!row||Object.keys(row).length!==4||typeof row.publicCellId!=='string'||!['today','this_week','earlier'].includes(row.timeBucket)||(row.residenceName!==null&&(typeof row.residenceName!=='string'||row.residenceName.length>100)))throw new Error('invalid');const community=communityForPublicCell(row.publicCellId);const neighbourhood=neighbourhoodForPublicCell(row.publicCellId);if(community)safe.push({community:neighbourhood?`${communityLabel(community,locale)} › ${communityLabel(neighbourhood,locale)}`:communityLabel(community,locale),communityId:neighbourhood?.id??community.id,place:row.residenceName,time:row.timeBucket});}if(active&&ticket===generation&&owner===await readSessionSubjectStrict())setActivities(safe);}catch{if(active&&ticket===generation)setFailed(true);}};void load();const off=subscribeSessionSubject(()=>void load());return()=>{active=false;generation++;off();};},[animalId,revision,locale]);
 return <View style={{gap:12}}><Text style={{fontSize:19,fontWeight:'700',color:c.ink}}>{cn?'社区足迹':'Community activity'}</Text>{activities.map((item,index)=><Pressable accessibilityRole="button" key={`${item.communityId}-${index}`} onPress={()=>router.push(`/map?communityId=${item.communityId}` as never)} style={{paddingVertical:10,borderBottomWidth:StyleSheet.hairlineWidth,borderColor:c.line,gap:4}}><Text style={{fontSize:16,fontWeight:'600',color:c.ink}}>{item.community}</Text>{item.place?<Text style={{fontSize:14,color:c.muted}}>{item.place}</Text>:null}<Text style={{fontSize:13,color:c.muted}}>{item.time==='today'?(cn?'最近延迟时段':'Latest delayed window'):item.time==='this_week'?(cn?'本周延迟活动':'This week, delayed'):(cn?'较早活动':'Earlier activity')}</Text></Pressable>)}{failed?<Pressable accessibilityRole="button" onPress={()=>setRevision(n=>n+1)}><Text style={{color:c.actionPrimary}}>{cn?'足迹暂不可用，点此重试':'Activity unavailable. Tap to retry.'}</Text></Pressable>:null}<Pressable accessibilityRole="button" accessibilityLabel={cn?'讨论这只猫':'Discuss this cat'} onPress={()=>router.push(`/community?catId=${animalId}` as never)} style={{backgroundColor:c.surface,borderRadius:18,minHeight:54,padding:16,flexDirection:'row',alignItems:'center',gap:12}}><AppIcon name="community" color={c.actionPrimary}/><Text style={{flex:1,color:c.ink,fontWeight:'600',fontSize:16}}>{cn?'讨论这只猫':'Discuss this cat'}</Text><AppIcon name="chevron" color={c.muted} size={16}/></Pressable></View>;
}
