import { catSampleLabel } from '../../src/i18n/cat-name';
import { PlaceSearch, MyLocationButton } from '../../src/maps/PlaceSearch';
import type { NearbyMapProps } from '../../src/maps/NearbyMap.types';
import type { SingaporeRegion } from '@animalhelper/domain';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Linking, Platform, PanResponder, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import {usesNativeLiquidTabs} from '../../src/navigation/native-tabs-policy';
import {tabBarOcclusion} from '../../src/navigation/tab-layout';
import { listPublicSightings, type PublicSighting, type NarrowRpcClient } from '../../src/api/feed';
import { getCatPresentations } from '../../src/api/cat-presentation';
import { getSightingPlaces, type SightingPlace } from '../../src/api/sighting-places';
import { getSupabaseClient } from '../../src/api/supabase';
import { readSessionSubjectStrict, subscribeSessionSubject } from '../../src/auth/session-subject';
import { AppIcon } from '../../src/components/AppIcon';
import { GlassSurface } from '../../src/design/GlassSurface';
import { useNativeColors } from '../../src/design/native-colors';
import { useLocale } from '../../src/i18n/LocaleContext';
import { NearbyMap } from '../../src/maps/NearbyMap';
import { buildSingaporeAreas, filterSingaporeAreas, communityLabel, SG_COMMUNITIES, SG_REGIONS, type SingaporeArea } from '../../src/maps/singapore-communities';

export default function MapScreen(){
 const insets=useSafeAreaInsets(); const overlayBottom=10+(usesNativeLiquidTabs(Platform.OS,Platform.Version)?insets.bottom:tabBarOcclusion(insets.bottom));
 const {locale}=useLocale(); const cn=locale==='zh-CN'; const router=useRouter(); const colors=useNativeColors(); const styles=makeStyles(colors);
 const localeRef=useRef(locale);localeRef.current=locale;
 const params=useLocalSearchParams<{communityId?:string}>();
 const desiredCommunity=SG_COMMUNITIES.some(area=>area.id===params.communityId)?params.communityId!:null;
 const client=getSupabaseClient() as unknown as NarrowRpcClient|null;
 const [areas,setAreas]=useState<readonly SingaporeArea[]>(()=>buildSingaporeAreas([],new Map(),locale));
 const [publicPortraits,setPublicPortraits]=useState(new Map<string, Readonly<{portraitUri?: string|null}>>());
 const [searchMode,setSearchMode]=useState<'cats'|'places'>('places');
 const [focusPoint,setFocusPoint]=useState<NearbyMapProps['focusPoint']>(null);
 const [region,setRegion]=useState<SingaporeRegion|'all'>('all'); const [query,setQuery]=useState('');
 const [selectedId,setSelectedId]=useState<string|null>(null); const [sheet,setSheet]=useState<'collapsed'|'half'|'full'>(desiredCommunity?'half':'collapsed'); const [filtersOpen,setFiltersOpen]=useState(false);
 const [clusterAreaIds,setClusterAreaIds]=useState<readonly string[]>([]);
 const [loading,setLoading]=useState(false); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState(false); const [hasMore,setHasMore]=useState(false); const [fitSingaporeRequest,setFitSingaporeRequest]=useState(0); const [headerHeight,setHeaderHeight]=useState(0); const [panelHeight,setPanelHeight]=useState(0);
 const rows=useRef<readonly PublicSighting[]>([]); const places=useRef(new Map<string,SightingPlace>()); const cursor=useRef<string|null>(null); const generation=useRef(0); const busy=useRef(false);
 const sheetPan=useRef(PanResponder.create({onMoveShouldSetPanResponder:(_,gesture)=>Math.abs(gesture.dy)>8,onPanResponderRelease:(_,gesture)=>{if(gesture.dy<-24)setSheet(value=>value==='collapsed'?'half':'full');if(gesture.dy>24)setSheet(value=>value==='full'?'half':'collapsed');}})).current;
 const load=useCallback(async(reset=true,refresh=false)=>{
   if(busy.current)return;
   const ticket=++generation.current; busy.current=true;setLoading(true);setError(false);
   if(refresh)setRefreshing(true);
   if(reset&&!refresh){rows.current=[];places.current=new Map();cursor.current=null;setHasMore(false);setSelectedId(desiredCommunity);setAreas(buildSingaporeAreas([],new Map(),localeRef.current));}
   try{
     if(!client)throw new Error('unconfigured');
     const owner=await readSessionSubjectStrict();
     const page=await listPublicSightings({limit:50,cursor:reset?null:cursor.current},client);
     const metadata=await getSightingPlaces(page.items.map(item=>item.sightingId),client);
     if(ticket!==generation.current || owner!==await readSessionSubjectStrict())return;
     const nextRows:readonly PublicSighting[]=reset?page.items:[...rows.current,...page.items]; const nextPlaces=reset?new Map(metadata):new Map(places.current);if(!reset)for(const [id,place] of metadata)nextPlaces.set(id,place);
     rows.current=nextRows;places.current=nextPlaces;cursor.current=page.nextCursor;setHasMore(page.items.length===50);setAreas(buildSingaporeAreas(nextRows,nextPlaces,localeRef.current));
     const ids=[...new Set(nextRows.map(item=>item.animalId))];const portraitPages=await Promise.all(Array.from({length:Math.ceil(ids.length/50)},(_,index)=>getCatPresentations(ids.slice(index*50,index*50+50))));const portraits=new Map(portraitPages.flatMap(page=>[...page]));
     if(ticket===generation.current && owner===await readSessionSubjectStrict())setPublicPortraits(portraits);
   }catch{if(ticket===generation.current)setError(true);}
   finally{if(ticket===generation.current){busy.current=false;setLoading(false);setRefreshing(false);}}
 },[client,desiredCommunity]);
 useEffect(()=>{setAreas(buildSingaporeAreas(rows.current,places.current,locale));},[locale]);
 useEffect(()=>{void load();const unsubscribe=subscribeSessionSubject(()=>{generation.current++;busy.current=false;rows.current=[];places.current=new Map();cursor.current=null;setPublicPortraits(new Map());setSelectedId(desiredCommunity);setClusterAreaIds([]);setAreas(buildSingaporeAreas([],new Map(),localeRef.current));void load();});return()=>{generation.current++;unsubscribe();};},[load,desiredCommunity]);
 const filtered=filterSingaporeAreas(areas,region,query); const selected=areas.find(area=>area.id===selectedId);
 const children=selected?areas.filter(area=>area.parentId===selected.id):[];
 const mapAreas=selected?[selected,...children]:filtered;
 const catCount=new Set(filtered.flatMap(area=>area.cats.map(cat=>cat.animalId))).size;
 const openCommunity=(area?:SingaporeArea)=>router.push((area?`/community?communitySlug=${area.id}`:'/community') as never);
 const selectArea=(id:string|null)=>{setSelectedId(id);if(id)setSheet('half');};
 const fitEdgePadding={top:insets.top+headerHeight+12,right:20,bottom:panelHeight+overlayBottom+12,left:20};
 return <View style={styles.screen}>
   <View style={StyleSheet.absoluteFill}><NearbyMap focusPoint={focusPoint} fitSingaporeRequest={fitSingaporeRequest} fitLayoutReady={headerHeight>0&&panelHeight>0} fitEdgePadding={fitEdgePadding} areas={mapAreas} publicPortraits={publicPortraits} selectedAreaId={selectedId} onSelectArea={id=>selectArea(id)} onSelectAreas={ids=>{setClusterAreaIds(ids);setSheet('half');}} fallbackLabel={cn?'地图暂不可用，下方仍可浏览社区。':'Map unavailable. Browse communities below.'}/></View>
   <SafeAreaView edges={['top']} style={[styles.overlay,{paddingBottom:overlayBottom}]} pointerEvents="box-none">
     <GlassSurface onLayout={event=>setHeaderHeight(event.nativeEvent.layout.height)} style={styles.header}>
       <View style={{flexDirection:'row',gap:8,alignItems:'center'}}><View style={{flex:1}}><PlaceSearch cn={cn} onSelect={place=>{selectArea(null);setFocusPoint({...place,title:place.name});}}/></View><Pressable accessibilityRole="button" accessibilityLabel={cn?'地图筛选':'Map filters'} onPress={()=>setFiltersOpen(open=>!open)} style={styles.icon}><AppIcon name="filters" color={colors.actionPrimary}/></Pressable></View>
       {filtersOpen?<><View style={{flexDirection:'row',gap:8}}>{(['places','cats'] as const).map(mode=><Pressable key={mode} accessibilityRole="button" accessibilityState={{selected:searchMode===mode}} onPress={()=>setSearchMode(mode)} style={[styles.chip,searchMode===mode&&styles.activeChip]}><Text style={[styles.chipText,searchMode===mode&&styles.activeText]}>{mode==='places'?(cn?'地点':'Places'):(cn?'社区与猫':'Communities & cats')}</Text></Pressable>)}</View>{searchMode==='cats'?<View style={styles.search}><AppIcon name="location" size={19} color={colors.muted}/><TextInput accessibilityLabel={cn?'搜索社区、猫或楼栋':'Search community, cat or building'} placeholder={cn?'社区、猫名、HDB / Condo':'Community, cat, HDB / Condo'} placeholderTextColor={colors.muted} value={query} onChangeText={value=>{setQuery(value);selectArea(null);setFocusPoint(null);}} style={styles.input}/></View>:null}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{[{id:'all' as const,en:'All',zh:'全岛'},...SG_REGIONS].map(item=><Pressable key={item.id} accessibilityRole="button" accessibilityState={{selected:region===item.id}} onPress={()=>{setRegion(item.id);selectArea(null);}} style={[styles.chip,region===item.id&&styles.activeChip]}><Text style={[styles.chipText,region===item.id&&styles.activeText]}>{cn?item.zh:item.en}</Text></Pressable>)}</ScrollView></>:null}
     </GlassSurface>
     <View style={styles.space} pointerEvents="box-none"><View style={styles.controls}><GlassSurface style={styles.round}><MyLocationButton cn={cn} onLocation={setFocusPoint}/></GlassSurface><GlassSurface style={styles.round}><Pressable accessibilityRole="button" accessibilityLabel={cn?'显示全岛':'Show all Singapore'} onPress={()=>{selectArea(null);setRegion('all');setQuery('');setFitSingaporeRequest(k=>k+1);setFocusPoint(null);}} style={styles.icon}><AppIcon name="fit" color={colors.actionPrimary}/></Pressable></GlassSurface></View></View>
     <View onLayout={event=>setPanelHeight(event.nativeEvent.layout.height)} style={[styles.panel,sheet==='collapsed'&&styles.collapsed,sheet==='full'&&styles.expanded]}>
       {sheet==='collapsed'?<><View pointerEvents="none" style={styles.collapsedGrip}><View style={styles.grip}/></View><View {...sheetPan.panHandlers} style={styles.collapsedHeader}><Pressable accessibilityRole="button" accessibilityLabel={cn?'展开附近活动':'Expand neighbourhood activity'} onPress={()=>setSheet('half')} style={styles.summary}><Text numberOfLines={1} style={styles.collapsedTitle}>{selected?communityLabel(selected,locale):(cn?'附近猫咪活动':'Neighbourhood cat activity')}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={cn?'展开地图列表':'Expand map list'} onPress={()=>setSheet('half')} style={styles.icon}><AppIcon name="expand" color={colors.actionPrimary}/></Pressable></View></>:<><View {...sheetPan.panHandlers} style={styles.gripRow}><View style={styles.grip}/><Pressable accessibilityRole="button" accessibilityLabel={cn?'收起地图列表':'Collapse map list'} onPress={()=>setSheet('collapsed')} style={styles.icon}><AppIcon name="collapse" color={colors.actionPrimary}/></Pressable></View>
       {focusPoint?<View style={styles.heading}><AppIcon name="location" color={colors.actionPrimary}/><Text style={[styles.name,{flex:1}]}>{focusPoint.title}</Text><Pressable accessibilityRole="button" onPress={()=>setFocusPoint(null)} style={styles.icon}><Text style={styles.chipText}>{cn?'关闭':'Close'}</Text></Pressable></View>:null}
       <View style={styles.heading}>{selected?<Pressable accessibilityRole="button" accessibilityLabel={cn?'返回社区列表':'Back to communities'} onPress={()=>setSelectedId(selected.parentId??null)} style={styles.icon}><AppIcon name="back" color={colors.actionPrimary}/></Pressable>:null}<View style={{flex:1}}><Text style={styles.panelTitle}>{selected?communityLabel(selected,locale):(cn?'探索社区':'Explore communities')}</Text><Text style={styles.meta}>{error?(cn?'活动暂未载入':'Activity not loaded'):selected?(cn?`${selected.cats.length} 只猫 · 延迟公开活动`:`${selected.cats.length} cats · delayed activity`):(cn?`${catCount} 只猫 · ${filtered.length} 个${query.trim()?'区域 / 邻里':'规划区'}`:`${catCount} cats · ${filtered.length} ${query.trim()?'areas / neighbourhoods':'planning areas'}`)}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={cn?'刷新':'Refresh'} onPress={()=>void load(true,true)} style={styles.icon}><AppIcon name="activity" color={colors.actionPrimary}/></Pressable></View>
       {loading?<ActivityIndicator accessibilityLabel={cn?'加载社区活动':'Loading community activity'} color={colors.actionPrimary}/>:null}
       {error?<Pressable accessibilityRole="button" onPress={()=>void load(true,true)}><Text style={styles.error}>{cn?'活动暂未载入，点此重试':'Activity could not load. Tap to retry.'}</Text></Pressable>:null}
       <ScrollView testID="map-list" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true,true)}/>} contentContainerStyle={styles.rows} showsVerticalScrollIndicator={false}>
         {clusterAreaIds.length>1&&!selected?<><Text style={styles.meta}>{cn?'选择一个邻里查看活动':'Choose a neighbourhood to view activity'}</Text>{areas.filter(area=>clusterAreaIds.includes(area.id)).map(area=><Pressable accessibilityRole="button" key={area.id} onPress={()=>{setClusterAreaIds([]);selectArea(area.id);}} style={styles.row}><Text style={styles.name}>{communityLabel(area,locale)}</Text><AppIcon name="chevron" size={16} color={colors.muted}/></Pressable>)}</>:selected?<>
           <Text style={styles.meta}>{selected.parentId?`${communityLabel(SG_COMMUNITIES.find(a=>a.id===selected.parentId)!,locale)} › ${communityLabel(selected,locale)}`:(cn?`${children.length} 个邻里`:`${children.length} neighbourhoods`)}</Text>
           {children.map(child=><Pressable key={child.id} accessibilityRole="button" onPress={()=>selectArea(child.id)} style={styles.row}><AppIcon name="location" color={colors.actionPrimary}/><View style={{flex:1}}><Text style={styles.name}>{communityLabel(child,locale)}</Text></View><Text style={styles.count}>{error?'—':child.cats.length}</Text><AppIcon name="chevron" size={16} color={colors.muted}/></Pressable>)}


           {selected.cats.map(cat=><Pressable accessibilityRole="button" key={cat.animalId} onPress={()=>router.push(`/cat/${cat.animalId}` as never)} style={styles.row}><View style={styles.avatar}><AppIcon name="cat" color={colors.actionPrimary}/></View><View style={{flex:1,gap:4}}><Text style={styles.name}>{cat.alias}</Text>{catSampleLabel(cat.animalId,locale)?<Text style={styles.meta}>{catSampleLabel(cat.animalId,locale)}</Text>:null}<Text style={styles.meta}>{cat.residenceType?`${cat.residenceType==='hdb'?'HDB':cat.residenceType==='condo'?'Condo':cn?'其他':'Other'} · ${cat.residenceName}`:cn?'楼栋信息未提供':'Building not provided'}</Text><Text style={styles.meta}>{cat.timeLabel}</Text></View><AppIcon name="chevron" color={colors.muted} size={16}/></Pressable>)}
           {!selected.cats.length&&!loading&&!error?<Text style={styles.meta}>{cn?'这里尚无已公开的猫记录。可报告目击，或发起社区讨论。':'No public cat records here yet. Report a sighting or start a discussion.'}</Text>:null}
           <View style={styles.actions}><Pressable accessibilityRole="button" onPress={()=>router.push('/report' as never)} style={styles.primary}><Text style={styles.primaryText}>{cn?'报告目击':'Report sighting'}</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>openCommunity(selected)} style={styles.secondary}><Text style={styles.chipText}>{cn?'社区讨论':'Discuss'}</Text></Pressable></View>
         </>:filtered.map(area=><Pressable accessibilityRole="button" accessibilityLabel={`${communityLabel(area,locale)}, ${area.cats.length} ${cn?'只猫':'cats'}`} key={area.id} onPress={()=>setSelectedId(area.id)} style={styles.row}><View style={styles.avatar}><AppIcon name="location" color={colors.actionPrimary}/></View><View style={{flex:1,gap:4}}><Text style={styles.name}>{communityLabel(area,locale)}</Text><Text style={styles.meta}>{area.parentId?`${SG_COMMUNITIES.find(p=>p.id===area.parentId)?.name} · ${cn?'邻里':'Neighbourhood'}`:SG_REGIONS.find(item=>item.id===area.region)?.[cn?'zh':'en']}</Text></View><Text style={styles.count}>{error?'—':area.cats.length}</Text><AppIcon name="chevron" size={16} color={colors.muted}/></Pressable>)}
         {!filtered.length?<Text style={styles.meta}>{cn?'没有匹配的社区、猫或楼栋。':'No matching community, cat or building.'}</Text>:null}
         {hasMore?<Pressable accessibilityRole="button" disabled={loading} onPress={()=>void load(false)} style={styles.secondary}><Text style={styles.chipText}>{cn?'载入更多活动':'Load more activity'}</Text></Pressable>:null}
         <Pressable accessibilityRole="link" onPress={()=>router.push('/community/geography' as never)}><Text style={styles.credit}>{cn?'社区与官方划分说明':'About communities and official boundaries'}</Text></Pressable>
         <Pressable accessibilityRole="link" onPress={()=>void Linking.openURL(selected?.parentId?'https://data.gov.sg/datasets/d_8594ae9ff96d0c708bc2af633048edfb/view':'https://data.gov.sg/datasets/d_2cc750190544007400b2cfd5d7f53209/view')}><Text style={styles.credit}>{selected?.parentId?'URA MP2019 · Subzones':'URA MP2025 · Planning areas'} · Singapore Open Data Licence</Text></Pressable>
         </ScrollView><Pressable accessibilityRole="button" accessibilityLabel={cn?'展开完整地图列表':'Show full map list'} onPress={()=>setSheet(value=>value==='half'?'full':'half')} style={styles.icon}><AppIcon name={sheet==='half'?'expand':'collapse'} color={colors.actionPrimary}/></Pressable></>}
     </View>
   </SafeAreaView>
 </View>;
}
const makeStyles=(c:ReturnType<typeof useNativeColors>)=>StyleSheet.create({screen:{flex:1,backgroundColor:c.canvas},overlay:{flex:1,paddingHorizontal:16,paddingBottom:10,gap:12},header:{borderRadius:28,padding:16,gap:12},heading:{flexDirection:'row',alignItems:'center',gap:8},kicker:{color:c.actionPrimary,fontWeight:'700',fontSize:10,letterSpacing:2},title:{color:c.ink,fontSize:22,fontWeight:'700',letterSpacing:-.4},search:{flexDirection:'row',alignItems:'center',gap:8,borderRadius:16,paddingHorizontal:12,backgroundColor:c.surface,minHeight:44},input:{flex:1,color:c.ink,fontSize:15,paddingVertical:10},chips:{gap:6},chip:{minHeight:44,paddingHorizontal:14,borderRadius:22,justifyContent:'center',backgroundColor:c.surface},chipText:{fontSize:14,fontWeight:'600',color:c.actionPrimary},activeChip:{backgroundColor:c.actionPrimary},activeText:{color:c.onAction},space:{flex:1,minHeight:40},controls:{alignSelf:'flex-end',gap:8},round:{borderRadius:24},icon:{width:44,minHeight:44,alignItems:'center',justifyContent:'center'},panel:{maxHeight:'48%',padding:18,gap:12,backgroundColor:c.surface,borderRadius:28,shadowColor:'#173A32',shadowOpacity:.10,shadowRadius:18,shadowOffset:{width:0,height:4}},collapsed:{height:76,maxHeight:76,paddingVertical:8,gap:4},expanded:{maxHeight:'80%',flex:1},gripRow:{height:20,alignItems:'center',justifyContent:'center'},collapsedGrip:{height:4,alignItems:'center',justifyContent:'center'},collapsedHeader:{height:44,flexDirection:'row',alignItems:'center'},grip:{width:36,height:4,borderRadius:2,backgroundColor:c.muted},summary:{flex:1,justifyContent:'center'},collapsedTitle:{fontSize:16,fontWeight:'700',color:c.ink},panelTitle:{fontSize:22,fontWeight:'700',color:c.ink},meta:{fontSize:13,lineHeight:19,color:c.muted},rows:{gap:2,paddingBottom:8},row:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:14,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:c.line},avatar:{width:44,height:44,borderRadius:16,backgroundColor:c.leafSoft,alignItems:'center',justifyContent:'center'},name:{fontSize:16,fontWeight:'600',color:c.ink},count:{fontSize:20,fontWeight:'700',color:c.actionPrimary},actions:{flexDirection:'row',gap:8,marginVertical:16},primary:{flex:1,minHeight:46,borderRadius:23,alignItems:'center',justifyContent:'center',backgroundColor:c.actionPrimary},primaryText:{fontSize:15,fontWeight:'600',color:c.onAction},secondary:{minHeight:46,paddingHorizontal:20,alignItems:'center',justifyContent:'center',borderRadius:23,backgroundColor:c.leafSoft},credit:{fontSize:10,lineHeight:16,color:c.muted,marginTop:14},error:{fontSize:13,lineHeight:19,color:c.actionPrimary}});
