import {useEffect,useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import {useRouter} from 'expo-router';
import {listDirectConversations,respondToDirectMessageRequest,type DirectConversation} from '../src/api/direct-messages';
import {useAccountSession} from '../src/auth/use-account-session';
import {ScreenScaffold} from '../src/components/ScreenScaffold';
import {useNativeColors} from '../src/design/native-colors';
import {useLocale} from '../src/i18n/LocaleContext';
import {randomUUID} from 'expo-crypto';
export default function Requests(){const {locale}=useLocale(),cn=locale==='zh-CN',c=useNativeColors(),router=useRouter(),auth=useAccountSession();const [rows,setRows]=useState<readonly DirectConversation[]>([]),[failed,setFailed]=useState(false);const load=async()=>{if(!auth.owner)return;try{const page=await listDirectConversations();if(await auth.pin()())setRows(page.items.filter(x=>x.status==='pending'));}catch{setFailed(true);}};useEffect(()=>{void load();},[auth.owner]);const respond=async(row:DirectConversation,accept:boolean)=>{try{await respondToDirectMessageRequest(row.conversationId,accept,randomUUID());if(await auth.pin()()){setRows(old=>old.filter(x=>x.conversationId!==row.conversationId));if(accept)router.replace(`/messages/${row.conversationId}` as never);}}catch{setFailed(true);}};return <ScreenScaffold compact title={cn?'消息请求':'Message requests'}><Pressable accessibilityRole="button" onPress={()=>router.back()} style={{minHeight:44,justifyContent:'center'}}><Text style={{color:c.actionPrimary}}>{cn?'返回':'Back'}</Text></Pressable>{failed?<Text style={{color:c.muted}}>{cn?'请求暂不可用。':'Requests unavailable.'}</Text>:null}{rows.map(row=><View key={row.conversationId} style={{paddingVertical:14,gap:8,borderBottomWidth:1,borderColor:c.line}}><Text style={{color:c.ink,fontWeight:'600'}}>{row.otherMember.name}</Text><Text style={{color:c.muted}}>{row.isIncoming?(cn?'想和你开始对话':'Wants to start a conversation'):(cn?'等待对方接受':'Waiting for their acceptance')}</Text>{row.isIncoming?<View style={{flexDirection:'row',gap:16}}><Pressable accessibilityRole="button" onPress={()=>void respond(row,true)} style={{minHeight:44,justifyContent:'center'}}><Text style={{color:c.actionPrimary,fontWeight:'600'}}>{cn?'接受':'Accept'}</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>void respond(row,false)} style={{minHeight:44,justifyContent:'center'}}><Text style={{color:c.muted}}>{cn?'拒绝':'Decline'}</Text></Pressable></View>:null}</View>)}{!failed&&!rows.length?<Text style={{color:c.muted}}>{cn?'没有待处理的消息请求。':'No pending message requests.'}</Text>:null}</ScreenScaffold>;}
