import { useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useEffect, useRef, useState } from 'react';
import { randomUUID } from 'expo-crypto';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { singaporeCommunities } from '@animalhelper/domain';

import { blockCommunityAuthor, createCommunityPost, deleteCommunityPost, listCommunityPosts, reportCommunityContent, type CommunityPost } from '../../src/api/community';
import { useAccountSession } from '../../src/auth/use-account-session';
import { AppIcon } from '../../src/components/AppIcon';
import { ScreenScaffold } from '../../src/components/ScreenScaffold';
import { useNativeColors } from '../../src/design/native-colors';

export default function CommunityScreen() {
  const colors = useNativeColors(); const styles = makeStyles(colors); const router = useRouter(); const auth = useAccountSession();
  const { communitySlug, catId } = useLocalSearchParams<{ communitySlug?: string; catId?: string }>();
  const [items, setItems] = useState<readonly CommunityPost[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [body, setBody] = useState(''); const [writing, setWriting] = useState(false); const [scope, setScope] = useState(communitySlug ?? ''); const [picking,setPicking]=useState(false); const postRequestId = useRef<string | null>(null); const postPayload=useRef<string|null>(null); const generation=useRef(0); const writingRef=useRef(false);
  const load = useCallback(async (more = false) => { const token=++generation.current; const current=auth.pin(); setLoading(true); setError(false); try { const page = await listCommunityPosts({ communitySlug: communitySlug ?? null, catId: catId ?? null, cursor: more ? cursor : null }); if(!await current()||token!==generation.current)return; setItems((old) => more ? [...old, ...page.items] : page.items); setCursor(page.nextCursor); } catch { if(await current()&&token===generation.current)setError(true); } finally { if(await current()&&token===generation.current)setLoading(false); } }, [auth.pin,catId,communitySlug,cursor]);
  useEffect(() => { generation.current++;setItems([]);setCursor(null);setBody('');postRequestId.current=null;void load(false); }, [communitySlug, catId, auth.owner]);
  const submit = async () => { if (!auth.owner || writingRef.current || (!catId && !scope.trim())) return; const current=auth.pin(); if(!await current())return; writingRef.current=true;setWriting(true); const payload=`${body.trim()}|${catId??''}|${communitySlug??scope.trim()}`; if(postPayload.current!==payload){postRequestId.current=null;postPayload.current=payload;} postRequestId.current ??= randomUUID(); try { await createCommunityPost(body, catId ?? null, communitySlug ?? scope.trim(), undefined, postRequestId.current); if(!await current())return; setBody(''); postRequestId.current=null;postPayload.current=null; await load(false); } catch { if(await current())setError(true); } finally { if(await current())setWriting(false); writingRef.current=false; } };
  return <ScreenScaffold title="Community" subtitle={communitySlug ? `Conversations in ${communitySlug}` : 'Neighbourhood cat care, in context.'} nativeAppearance>
    {auth.owner ? <View style={styles.composer}>{!catId && !communitySlug ? <><Pressable accessibilityRole="button" onPress={()=>setPicking(!picking)} style={styles.area}><Text style={styles.link}>{singaporeCommunities.find(x=>x.id===scope)?.name ?? 'Choose community'}</Text></Pressable>{picking?<View style={styles.areas}>{singaporeCommunities.map(area=><Pressable key={area.id} onPress={()=>{setScope(area.id);setPicking(false);}}><Text style={styles.areaName}>{area.name}</Text></Pressable>)}</View>:null}</> : null}<View style={styles.composerRow}><TextInput accessibilityLabel="Start a discussion" value={body} onChangeText={setBody} multiline placeholder="Start a discussion" placeholderTextColor={colors.muted} style={styles.input} editable={!writing}/><Pressable accessibilityRole="button" accessibilityLabel="Post" disabled={!body.trim() || writing || (!catId && !scope.trim())} onPress={() => void submit()} style={styles.send}><AppIcon name="send" size={18} color={colors.actionPrimary} /></Pressable></View></View> : <Text style={styles.note}>Sign in and confirm you are 18+ to join the conversation.</Text>}
    {loading && !items.length ? <ActivityIndicator color={colors.actionPrimary} /> : null}
    {error ? <View style={styles.state}><Text style={styles.note}>We could not load this conversation.</Text><Pressable onPress={() => void load(false)}><Text style={styles.link}>Try again</Text></Pressable></View> : null}
    {!loading && !error && !items.length ? <Text style={styles.note}>No discussions here yet. Start with something helpful for your neighbours.</Text> : null}
    {items.map((post) => <View key={post.postId} style={styles.post}><Pressable accessibilityRole="button" onPress={() => router.push({ pathname: '/community/[id]', params: { id: post.postId } })} style={styles.postOpen}><View style={styles.meta}><Text style={styles.author}>{post.author.name}</Text><Text style={styles.muted}>{new Date(post.createdAt).toLocaleDateString()}</Text></View><Text style={styles.body}>{post.body}</Text><Text style={styles.muted}>{post.replyCount} {post.replyCount === 1 ? 'reply' : 'replies'}</Text></Pressable>{auth.owner ? <View style={styles.actions}>{post.canDelete ? <Pressable accessibilityRole="button" onPress={() => void deleteCommunityPost(post.postId).then(() => load(false)).catch(() => setError(true))}><Text style={styles.link}>Delete</Text></Pressable> : <><Pressable accessibilityRole="button" onPress={() => void blockCommunityAuthor('community_post', post.postId).then(() => load(false)).catch(() => setError(true))}><Text style={styles.link}>Block author</Text></Pressable><Pressable accessibilityRole="button" onPress={() => Alert.alert('Report post', 'Choose a reason', [{ text: 'Spam', onPress: () => void reportCommunityContent('community_post', post.postId, 'spam').catch(() => setError(true)) }, { text: 'Harassment', onPress: () => void reportCommunityContent('community_post', post.postId, 'harassment').catch(() => setError(true)) }, { text: 'Unsafe location', onPress: () => void reportCommunityContent('community_post', post.postId, 'precise_location_exposure').catch(() => setError(true)) }, { text: 'Cancel', style: 'cancel' }])}><Text style={styles.link}>Report</Text></Pressable></>}</View> : null}</View>)}
    {cursor ? <Pressable accessibilityRole="button" disabled={loading} onPress={() => void load(true)} style={styles.more}><Text style={styles.link}>{loading ? 'Loading…' : 'Load more'}</Text></Pressable> : null}
  </ScreenScaffold>;
}
const makeStyles = (c: ReturnType<typeof useNativeColors>) => StyleSheet.create({ composer:{backgroundColor:c.surface,borderRadius:16,padding:12,gap:8},composerRow:{flexDirection:'row',alignItems:'flex-end',gap:8},area:{minHeight:44,justifyContent:'center'},areas:{maxHeight:240,gap:12},areaName:{fontSize:16,color:c.ink}, input:{flex:1,minHeight:44,color:c.ink,fontSize:17,lineHeight:23},send:{width:44,height:44,alignItems:'center',justifyContent:'center'},post:{paddingVertical:16,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:c.line,gap:8},postOpen:{gap:8},actions:{flexDirection:'row',justifyContent:'flex-end'},meta:{flexDirection:'row',justifyContent:'space-between',gap:12},author:{fontSize:17,fontWeight:'600',color:c.ink},body:{fontSize:17,lineHeight:24,color:c.ink},muted:{fontSize:13,color:c.muted},note:{fontSize:16,lineHeight:23,color:c.muted},link:{fontSize:17,color:c.actionPrimary,fontWeight:'600'},state:{gap:8},more:{minHeight:44,justifyContent:'center',alignItems:'center'} });
