import { ProfileAvatar } from '../../src/profile/ProfileAvatar';
import { getCommunityAvatars } from '../../src/api/community-avatar';
import { getCommunityReactions, type CommunityReaction } from '../../src/api/community-reactions';
import { CommunityLike } from '../../src/community/CommunityLike';
import { getCatPresentations, type CatPresentation } from '../../src/api/cat-presentation';
import { listPublicSightings, type PublicSighting } from '../../src/api/feed';
import { localizedCatName } from '../../src/i18n/cat-name';
import {SG_COMMUNITIES as singaporeCommunities, browseSingaporeCommunities, communityLabel} from '../../src/maps/singapore-communities';
import {randomUUID} from 'expo-crypto';
import {useFocusEffect,useLocalSearchParams,useRouter} from 'expo-router';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Image,Modal,ScrollView,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {createCommunityPost,listCommunityPosts,type CommunityPost} from '../../src/api/community';
import {useAccountSession} from '../../src/auth/use-account-session';
import {CommunityContentActions} from '../../src/community/CommunityContentActions';
import {AppIcon} from '../../src/components/AppIcon';
import {ScreenScaffold} from '../../src/components/ScreenScaffold';
import {GlassSurface} from '../../src/design/GlassSurface';
import {useNativeColors} from '../../src/design/native-colors';
import {useLocale} from '../../src/i18n/LocaleContext';
import {profileAvatarKey} from '../../src/profile/profile-avatar';

export default function CommunityScreen({ compose = false }: { compose?: boolean }){
 const c=useNativeColors(),s=styles(c),router=useRouter(),auth=useAccountSession();const {locale}=useLocale();const zh=locale==='zh-CN';
 const [avatars,setAvatars]=useState(new Map<string,string>());
 const [reactions,setReactions]=useState(new Map<string,CommunityReaction>());
 const [selectedCat,setSelectedCat]=useState<string|null>(null);
 const [portraits,setPortraits]=useState(new Map<string,CatPresentation>());
 const [cats,setCats]=useState<readonly PublicSighting[]>([]);
 const params=useLocalSearchParams<{communitySlug?:string;catId?:string}>();const communitySlug=typeof params.communitySlug==='string'?params.communitySlug:null,catId=typeof params.catId==='string'?params.catId:compose?selectedCat:null;
 const [items,setItems]=useState<readonly CommunityPost[]>([]),[cursor,setCursor]=useState<string|null>(null),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[notice,setNotice]=useState(''),[body,setBody]=useState(''),[writing,setWriting]=useState(false),[scope,setScope]=useState(communitySlug??''),[picker,setPicker]=useState(false),[search,setSearch]=useState(''),[scopeParent,setScopeParent]=useState<string|null>(null);
 const generation=useRef(0),busy=useRef(false),alive=useRef(true),context=useRef('');context.current=JSON.stringify([auth.owner,communitySlug,catId]);const pending=useRef<{key:string;id:string}|null>(null);
 const load=useCallback(async(more=false)=>{
   const token=++generation.current,current=auth.pin();setLoading(true);setFailed(false);
   try{const page=await listCommunityPosts({communitySlug,catId,cursor:more?cursor:null});const [photos,likes,postPictures]=await Promise.all([getCommunityAvatars('community_post',page.items.map(p=>p.postId)).catch(()=>new Map<string,string>()),getCommunityReactions(page.items.map(p=>p.postId)).catch(()=>new Map<string,CommunityReaction>()),getCatPresentations(page.items.flatMap(p=>p.catId?[p.catId]:[]))]);if(alive.current&&token===generation.current&&await current()){setItems(old=>more?[...old,...page.items]:page.items);setAvatars(old=>more?new Map([...old,...photos]):photos);setReactions(old=>more?new Map([...old,...likes]):likes);setPortraits(old=>new Map([...old,...postPictures]));setCursor(page.items.length===20?page.nextCursor:null);}}
   catch{if(alive.current&&token===generation.current&&await current())setFailed(true);}
   finally{if(alive.current&&token===generation.current&&await current())setLoading(false);}
 },[auth.pin,communitySlug,catId,cursor]);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;};},[]);
 useEffect(()=>{generation.current++;busy.current=false;setWriting(false);setItems([]);setAvatars(new Map());setReactions(new Map());setCursor(null);setBody('');setNotice('');setScope(communitySlug??'');setSelectedCat(null);pending.current=null;if(auth.owner!==undefined)void load();},[auth.owner,communitySlug,params.catId]);
 useFocusEffect(useCallback(()=>{ if(auth.owner!==undefined) void load(); },[auth.owner,communitySlug]));
 useEffect(()=>{let active=true;const current=auth.pin();setCats([]);setPortraits(new Map());if(auth.owner===undefined)return;void listPublicSightings({limit:20}).then(async page=>{const unique=[...new Map(page.items.map(cat=>[cat.animalId,cat])).values()];const pictures=await getCatPresentations(unique.map(cat=>cat.animalId));if(active&&await current()){setCats(unique);setPortraits(old=>new Map([...old,...pictures]));}}).catch(()=>{});return()=>{active=false;};},[auth.owner]);
 const submit=async()=>{
   if(!auth.owner||busy.current||!body.trim()||(!catId&&!scope))return;busy.current=true;setWriting(true);const current=auth.pin(),screenContext=context.current;
   try{if(!await current())return;const selected=communitySlug??(scope||null);const key=JSON.stringify([auth.owner,body.trim(),catId,selected]);if(pending.current?.key!==key)pending.current={key,id:randomUUID()};await createCommunityPost(body,catId,selected,undefined,pending.current.id);if(alive.current&&screenContext===context.current&&await current()){pending.current=null;setBody('');setNotice(zh?'已发布':'Posted');router.replace((catId?`/community?catId=${catId}`:selected?`/community?communitySlug=${selected}`:'/discuss') as never);}}
   catch{if(alive.current&&screenContext===context.current&&await current())setNotice(zh?'发布未完成，内容已保留。请确认贡献资格后重试。':'Post not completed. Your text is kept. Check contributor eligibility and retry.');}
   finally{if(screenContext===context.current){busy.current=false;if(alive.current)setWriting(false);}}
 };
 const label=(id:string|null)=>{const area=singaporeCommunities.find(a=>a.id===id);return area?communityLabel(area,locale):undefined;};
 const communityName=label(communitySlug);
 const pickScope=(id:string)=>{setPicker(false);if(compose)setScope(id);else router.setParams({communitySlug:id});};
 const newPostPath = `/community/new${communitySlug?`?communitySlug=${communitySlug}`:catId?`?catId=${catId}`:''}`;
 return <ScreenScaffold trailing={compose||communitySlug||catId?<Pressable accessibilityRole="button" accessibilityLabel={zh?'返回':'Back'} onPress={()=>router.canGoBack()?router.back():router.replace('/discuss' as never)} style={{minWidth:44,minHeight:44,alignItems:'center',justifyContent:'center'}}><AppIcon name="close" color={c.actionPrimary}/></Pressable>:<Pressable accessibilityRole="button" accessibilityLabel={zh?'发布帖子':'New post'} onPress={()=>router.push(newPostPath as never)} style={s.send}><AppIcon name="send" color={c.onAction} size={18}/><Text style={s.sendText}>{zh?'发布':'Post'}</Text></Pressable>} title={compose?(zh?'发布帖子':'New post'):(zh?'社区':'Community')} subtitle={communityName??(catId?(zh?'围绕这只猫的讨论':'Conversations about this cat'):undefined)}>

   {auth.failed?<Pressable accessibilityRole="button" onPress={()=>void auth.reload()} style={s.touch}><Text style={s.link}>{zh?'重试账户连接':'Retry account connection'}</Text></Pressable>:null}
   {compose&&auth.owner?<GlassSurface style={s.composer}>
     {!catId&&!communitySlug?<Pressable accessibilityRole="button" disabled={writing} onPress={()=>setPicker(true)} style={s.scope}><AppIcon name="location" size={18} color={c.actionPrimary}/><Text style={s.link}>{label(scope)??(zh?'选择社区':'Choose community')}</Text><AppIcon name="chevron" size={16} color={c.muted}/></Pressable>:null}
     {!params.catId?<View style={{gap:8}}><Text style={s.meta}>{zh?'关联猫咪（可选）':'Add a cat (optional)'}</Text><ScrollView horizontal contentContainerStyle={{gap:8}}>{cats.map(cat=><Pressable key={cat.animalId} disabled={writing} accessibilityRole="button" accessibilityState={{selected:selectedCat===cat.animalId}} onPress={()=>setSelectedCat(selectedCat===cat.animalId?null:cat.animalId)} style={[s.scope,{paddingHorizontal:12,borderRadius:22,backgroundColor:selectedCat===cat.animalId?c.leafSoft:c.surface}]}><AppIcon name="cat" size={18} color={c.actionPrimary}/><Text style={s.link}>{localizedCatName(cat.animalId,cat.primaryAlias,locale)}</Text></Pressable>)}</ScrollView></View>:null}
     <TextInput accessibilityLabel={zh?'发起讨论':'Start a discussion'} value={body} onChangeText={setBody} multiline maxLength={2000} editable={!writing} placeholder={zh?'分享一个发现，或问个问题…':'Share a discovery or ask a question…'} placeholderTextColor={c.muted} style={s.input}/>
     <View style={s.composerFooter}><Text style={s.meta}>{body.length}/2000</Text><Pressable accessibilityRole="button" accessibilityLabel={zh?'发布':'Post'} disabled={writing||!body.trim()||(!catId&&!scope)} onPress={()=>void submit()} style={s.send}><Text style={s.sendText}>{zh?'发布':'Post'}</Text><AppIcon name="send" size={18} color={c.onAction}/></Pressable></View>
   </GlassSurface>:compose&&auth.owner===null?<Pressable accessibilityRole="button" onPress={()=>router.push('/profile' as never)} style={s.signin}><Text style={s.link}>{zh?'登录并完善资料，参与讨论':'Sign in and complete your profile to join'}</Text></Pressable>:null}
   {!compose?<>
     {communitySlug||catId?<Pressable accessibilityRole="button" accessibilityLabel={zh?'发布帖子':'New post'} onPress={()=>router.push(newPostPath as never)} style={[s.send,{alignSelf:'flex-start'}]}><AppIcon name="send" color={c.onAction} size={18}/><Text style={s.sendText}>{zh?'发布':'Post'}</Text></Pressable>:null}
     <View style={{flexDirection:'row',gap:16}}><Pressable accessibilityRole="button" onPress={()=>router.setParams({communitySlug:undefined,catId:undefined})} style={s.touch}><Text style={s.link}>{zh?'全岛':'All'}</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>setPicker(true)} style={s.touch}><Text style={s.link}>{communityName??(zh?'选择邻里':'Choose neighbourhood')}</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>{void load();}} style={s.touch}><Text style={s.link}>{zh?'刷新':'Refresh'}</Text></Pressable></View>
     {!catId&&cats.length?<View style={{gap:12}}><Text style={s.author}>{zh?'认识社区里的猫':'Meet the neighbourhood cats'}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:14}}>{cats.slice(0,8).map(cat=><Pressable accessibilityRole="button" key={cat.animalId} onPress={()=>router.push(`/community?catId=${cat.animalId}` as never)} style={{width:86,gap:6,alignItems:'center'}}>{portraits.get(cat.animalId)?.portraitUri?<Image source={{uri:portraits.get(cat.animalId)!.portraitUri}} style={{width:72,height:72,borderRadius:36}}/>:<View style={[s.avatar,{width:72,height:72,borderRadius:36}]}><AppIcon name="cat" size={32} color={c.actionPrimary}/></View>}<Text numberOfLines={1} style={s.meta}>{localizedCatName(cat.animalId,cat.primaryAlias,locale)}</Text>{portraits.get(cat.animalId)?.sampleLabel?<Text style={s.meta}>{zh?'测试样本':'Test sample'}</Text>:null}</Pressable>)}</ScrollView></View>:null}
   </>:null}
   {notice?<Text accessibilityLiveRegion="polite" style={s.note}>{notice}</Text>:null}
   {!compose&&loading&&!items.length?<ActivityIndicator color={c.actionPrimary}/>:null}
   {!compose&&failed?<Pressable accessibilityRole="button" onPress={()=>void load()} style={s.touch}><Text style={s.link}>{zh?'讨论暂未载入，点此重试':'Conversations did not load. Tap to retry.'}</Text></Pressable>:null}
   {!compose&&!loading&&!failed&&!items.length?<View style={s.empty}><AppIcon name="community" size={36} color={c.actionPrimary}/><Text style={s.note}>{zh?'这里还没有帖子。发现了什么有趣的事？':'No posts here yet. What have you spotted?'}</Text></View>:null}
   {(!compose?items:[]).map(post=><View key={post.postId} style={s.post}>
     <View style={s.metaRow}><ProfileAvatar avatarKey={post.author.avatarKey} photoUri={avatars.get(post.postId)} size={42}/><View style={{flex:1}}><Text style={s.author}>{post.author.name}</Text><Text style={s.meta}>{label(post.communitySlug)??(zh?'猫咪讨论':'Cat discussion')} · {new Date(post.createdAt).toLocaleDateString(zh?'zh-SG':'en-SG',{month:'short',day:'numeric'})}</Text></View>{auth.owner?<CommunityContentActions type="community_post" id={post.postId} canDelete={post.canDelete} zh={zh} pin={auth.pin} onChanged={()=>load()} onNotice={setNotice}/>:null}</View>
     <Pressable accessibilityRole="button" accessibilityLabel={zh?'打开讨论':'Open discussion'} onPress={()=>router.push(`/community/${post.postId}` as never)} style={s.postOpen}><Text style={s.body}>{post.body}</Text>{post.catId&&portraits.get(post.catId)?.portraitUri?<Image source={{uri:portraits.get(post.catId)!.portraitUri}} style={{width:'100%',aspectRatio:1,borderRadius:14}}/>:null}{post.catId?<Text style={s.link}>{zh?'猫咪讨论':'Cat discussion'}</Text>:null}<View style={s.replyRow}><AppIcon name="reply" size={18} color={c.muted}/><Text style={s.meta}>{post.replyCount} {zh?'条回复':'replies'}</Text></View></Pressable>
     {reactions.get(post.postId)?<CommunityLike reaction={reactions.get(post.postId)!} zh={zh} owner={auth.owner} pin={auth.pin} onChange={next=>setReactions(old=>new Map(old).set(post.postId,next))} onSignIn={()=>router.push('/profile' as never)} onError={()=>setNotice(zh?'点赞未保存，请重试。':'Like was not saved. Please retry.')}/>:null}
   </View>)}
   {!compose&&cursor?<Pressable accessibilityRole="button" disabled={loading} onPress={()=>void load(true)} style={s.touch}><Text style={s.link}>{zh?'载入更多':'Load more'}</Text></Pressable>:null}
   <Modal visible={picker} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setPicker(false)}><ScreenScaffold title={zh?'选择社区':'Choose community'} trailing={<Pressable accessibilityRole="button" onPress={()=>setPicker(false)} style={s.touch}><Text style={s.link}>{zh?'完成':'Done'}</Text></Pressable>}>
     <TextInput accessibilityLabel={zh?'搜索社区':'Search communities'} placeholder={zh?'例如：西海岸、金文泰':'Try West Coast or Clementi'} placeholderTextColor={c.muted} value={search} onChangeText={setSearch} style={s.search}/>
     {scopeParent&&!search.trim()?<><Pressable accessibilityRole="button" onPress={()=>setScopeParent(null)} style={s.touch}><Text style={s.link}>{zh?'返回所有规划区':'Back to planning areas'}</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>{pickScope(scopeParent);}} style={s.areaRow}><Text style={s.author}>{zh?'整个':'All of'} {label(scopeParent)}</Text></Pressable></>:null}
     {browseSingaporeCommunities(search,scopeParent).map(area=><Pressable accessibilityRole="button" accessibilityLabel={communityLabel(area,locale)} accessibilityState={{selected:scope===area.id}} key={area.id} onPress={()=>{if(!area.parentId){setScopeParent(area.id);setSearch('');}else{pickScope(area.id);}}} style={s.areaRow}><View><Text style={s.author}>{communityLabel(area,locale)}</Text>{area.parentId?<Text style={s.meta}>{label(area.parentId)} · {zh?'邻里':'Neighbourhood'}</Text>:null}</View><AppIcon name={scope===area.id?'check':'chevron'} color={c.actionPrimary}/></Pressable>)}
   </ScreenScaffold></Modal>
 </ScreenScaffold>;
}
const styles=(c:ReturnType<typeof useNativeColors>)=>StyleSheet.create({composer:{borderRadius:24,padding:16,gap:10},scope:{minHeight:44,flexDirection:'row',alignItems:'center',gap:8},input:{minHeight:80,fontSize:17,lineHeight:24,color:c.ink},composerFooter:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},send:{minHeight:44,paddingHorizontal:18,gap:8,borderRadius:22,flexDirection:'row',alignItems:'center',backgroundColor:c.actionPrimary},sendText:{color:c.onAction,fontWeight:'600'},post:{paddingVertical:20,gap:12,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:c.line},metaRow:{flexDirection:'row',alignItems:'center',gap:10},avatar:{width:42,height:42,borderRadius:15,backgroundColor:c.leafSoft,alignItems:'center',justifyContent:'center'},author:{fontSize:16,fontWeight:'600',color:c.ink},meta:{fontSize:12,lineHeight:18,color:c.muted},body:{fontSize:17,lineHeight:27,color:c.ink},postOpen:{gap:18},replyRow:{flexDirection:'row',alignItems:'center',gap:6},link:{fontSize:15,fontWeight:'600',color:c.actionPrimary},note:{fontSize:15,lineHeight:23,color:c.muted},touch:{minHeight:44,justifyContent:'center'},empty:{paddingVertical:26,alignItems:'center',gap:14},signin:{padding:18,borderRadius:20,backgroundColor:c.leafSoft},search:{minHeight:46,color:c.ink,backgroundColor:c.surface,borderRadius:16,paddingHorizontal:14},areaRow:{minHeight:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:StyleSheet.hairlineWidth,borderColor:c.line}});
