import {useCallback,useEffect,useRef,useState} from 'react';
import {AppState,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {useLocalSearchParams,useRouter} from 'expo-router';
import {randomUUID} from 'expo-crypto';
import {getDirectConversation,listDirectMessages,markDirectConversationRead,sendDirectMessage,type DirectMessage} from '../../src/api/direct-messages';
import {useAccountSession} from '../../src/auth/use-account-session';
import {ScreenScaffold} from '../../src/components/ScreenScaffold';
import {GlassSurface} from '../../src/design/GlassSurface';
import {useNativeColors} from '../../src/design/native-colors';
const merge=(old:readonly DirectMessage[],next:readonly DirectMessage[])=>[...new Map([...old,...next].map(x=>[x.messageId,x])).values()].sort((a,b)=>Date.parse(a.sentAt)-Date.parse(b.sentAt));
export default function MessageThread(){const {id}=useLocalSearchParams<{id:string}>(),router=useRouter(),auth=useAccountSession(),c=useNativeColors();const [messages,setMessages]=useState<readonly DirectMessage[]>([]),[cursor,setCursor]=useState<string|null>(null),[text,setText]=useState(''),[failed,setFailed]=useState(false),[name,setName]=useState('');const sending=useRef<{body:string;requestId:string}|null>(null),busy=useRef(false);
 const load=useCallback(async(more=false)=>{if(!auth.owner||!id)return;const pin=auth.pin();try{const [conversation,page]=await Promise.all([getDirectConversation(id),listDirectMessages(id,more?cursor:null)]);if(await pin()){setName(conversation.otherMember.name);setMessages(old=>more?merge(page.items,old):page.items);setCursor(page.nextCursor);setFailed(false);const anchor=page.items.at(-1);if(anchor)void markDirectConversationRead(id,anchor.messageId).catch(()=>undefined);}}catch{if(await pin())setFailed(true);}},[auth.owner,auth.pin,cursor,id]);
 useEffect(()=>{setMessages([]);setCursor(null);if(auth.owner)void load();},[id,auth.owner]);useEffect(()=>{const state=AppState.addEventListener('change',v=>{if(v==='active')void load();});const timer=setInterval(()=>{if(AppState.currentState==='active')void load();},15000);return()=>{state.remove();clearInterval(timer);};},[load]);const send=async()=>{if(!text.trim()||busy.current||!id)return;busy.current=true;const draft=sending.current?.body===text.trim()?sending.current:{body:text.trim(),requestId:randomUUID()};sending.current=draft;try{const sent=await sendDirectMessage(id,draft.body,draft.requestId);if(await auth.pin()()){setMessages(old=>merge(old,[{messageId:sent.messageId,body:draft.body,sentAt:sent.sentAt,isMine:true,requestId:draft.requestId,cursor:sent.messageId}]));setText('');sending.current=null;}}catch{setFailed(true);}finally{busy.current=false;}};return <ScreenScaffold compact title={name||'Messages'} onRefresh={()=>void load()}><Pressable accessibilityRole="button" onPress={()=>router.back()} style={s.touch}><Text style={{color:c.actionPrimary}}>Back</Text></Pressable><ScrollView contentContainerStyle={{gap:8}}>{cursor?<Pressable accessibilityRole="button" onPress={()=>void load(true)} style={s.touch}><Text style={{color:c.actionPrimary}}>Load earlier</Text></Pressable>:null}{messages.map(m=><View key={m.messageId} style={[s.bubble,{backgroundColor:m.isMine?c.actionPrimary:c.surface,alignSelf:m.isMine?'flex-end':'flex-start'}]}><Text style={{color:m.isMine?c.onAction:c.ink}}>{m.body}</Text><Text style={{color:m.isMine?c.onAction:c.muted,fontSize:11}}>{new Date(m.sentAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</Text></View>)}</ScrollView>{failed?<Text style={{color:c.muted}}>Message not sent. Keep the text and retry.</Text>:null}<GlassSurface style={s.compose}><TextInput accessibilityLabel="Write a message" value={text} onChangeText={setText} multiline style={[s.input,{color:c.ink}]}/><Pressable accessibilityRole="button" onPress={()=>void send()} style={[s.send,{backgroundColor:c.actionPrimary}]}><Text style={{color:c.onAction}}>Send</Text></Pressable></GlassSurface></ScreenScaffold>;}
const s=StyleSheet.create({touch:{minHeight:44,justifyContent:'center',alignSelf:'flex-start'},bubble:{maxWidth:'82%',borderRadius:18,paddingHorizontal:14,paddingVertical:10,gap:4},compose:{flexDirection:'row',alignItems:'flex-end',gap:8,padding:10,borderRadius:24},input:{flex:1,minHeight:44,fontSize:16},send:{minWidth:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center',paddingHorizontal:10}});
