import { useState } from 'react';
import { useRouter } from 'expo-router';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import type { CatPage } from '../api/follows';
import { AppIcon } from '../components/AppIcon';
import { useNativeColors } from '../design/native-colors';
import { getCommunityMapCopy } from '../i18n/catalog';
import { useLocale } from '../i18n/LocaleContext';
export type CatPresentation = Readonly<{ portraitUri?: string | null; sampleLabel?: string | null }>;
export function CatList({page,loading,failed,refresh,more,empty,presentations=new Map()}:{page:CatPage;loading:boolean;failed:boolean;refresh:()=>void;more:()=>void;empty:string;presentations?:ReadonlyMap<string,CatPresentation>}){
 const {locale}=useLocale();const cn=locale==='zh-CN';const router=useRouter();const copy=getCommunityMapCopy(locale);
 const colors=useNativeColors();const styles=makeStyles(colors);const [failedUris,setFailedUris]=useState<Set<string>>(new Set());const markFailed=(uri:string)=>setFailedUris(previous=>new Set([...previous,uri]));
 return <View style={styles.container}><Pressable accessibilityRole="button" style={styles.refresh} disabled={loading} onPress={refresh}><Text style={styles.refreshText}>{cn?'刷新':'Refresh'}</Text></Pressable>
 {loading?<Text accessibilityLiveRegion="polite" style={styles.note}>{cn?'正在加载…':'Loading…'}</Text>:null}
 {failed?<Text accessibilityRole="alert" style={styles.error}>{cn?'加载失败，请刷新重试。':'Could not load cats. Refresh to retry.'}</Text>:null}
 {!loading&&!failed&&page.items.length===0?<Text style={styles.note}>{empty}</Text>:null}
 {page.items.map((cat,index)=>{const presentation=presentations.get(cat.animalId);const candidate=presentation?.portraitUri;const uri=candidate&&!failedUris.has(candidate)?candidate:null;return <Pressable key={cat.animalId} accessibilityRole="button" accessibilityLabel={cn?`查看 ${cat.primaryAlias}`:`View ${cat.primaryAlias}`} style={({pressed})=>[index===0&&uri?styles.hero:styles.row,pressed&&styles.pressed]} onPress={()=>router.push(`/cat/${cat.animalId}` as never)}>{index===0&&uri?<><Image accessibilityLabel={presentation?.sampleLabel??`${cat.primaryAlias} public portrait`} source={{uri}} onError={()=>markFailed(uri)} resizeMode="cover" style={styles.heroImage}/><View style={styles.heroShade}/><View style={styles.heroCopy}><Text style={styles.heroName}>{cat.primaryAlias}</Text><Text style={styles.heroMeta}>{copy.verificationLabel(cat.verification)} · {cat.timeBucket?copy.timeLabel(cat.timeBucket):(cn?'暂无公开活动':'No public activity yet')}</Text></View></>:<><View style={styles.thumbnail}>{uri?<Image accessibilityLabel={presentation?.sampleLabel??`${cat.primaryAlias} public portrait`} source={{uri}} onError={()=>markFailed(uri)} resizeMode="cover" style={styles.thumbnailImage}/>:<AppIcon name="cat" size={27} color={colors.actionPrimary}/>}</View><View style={styles.copy}><Text style={styles.name}>{cat.primaryAlias}</Text><Text style={styles.meta}>{cat.timeBucket ? copy.timeLabel(cat.timeBucket) : (cn?'暂无公开活动':'No public activity yet')}</Text></View><Text style={styles.badge}>{copy.verificationLabel(cat.verification)}</Text></>}</Pressable>;})}
 {page.nextCursor?<Pressable accessibilityRole="button" style={styles.refresh} disabled={loading} onPress={more}><Text style={styles.refreshText}>{cn?'加载更多猫':'Load more cats'}</Text></Pressable>:null}</View>;
}
const makeStyles=(colors:ReturnType<typeof useNativeColors>)=>StyleSheet.create({container:{gap:4},refresh:{minHeight:44,alignSelf:'flex-start',justifyContent:'center',paddingHorizontal:10},refreshText:{color:colors.actionPrimary,fontSize:16,fontWeight:'600'},note:{color:colors.muted,fontSize:15,lineHeight:21,paddingVertical:12},error:{color:colors.danger,fontSize:15,lineHeight:21,paddingVertical:12},hero:{height:300,borderRadius:24,overflow:'hidden',justifyContent:'flex-end',backgroundColor:colors.leafSoft,marginBottom:8},heroImage:{...StyleSheet.absoluteFill,width:'100%',height:'100%'},heroShade:{...StyleSheet.absoluteFill,backgroundColor:'rgba(0,0,0,.18)'},heroCopy:{padding:20,gap:4},heroName:{color:'#FFFFFF',fontSize:28,lineHeight:34,fontWeight:'700'},heroMeta:{color:'#FFFFFF',fontSize:14,lineHeight:20,fontWeight:'600'},row:{minHeight:80,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line},thumbnail:{width:56,height:56,borderRadius:16,overflow:'hidden',alignItems:'center',justifyContent:'center',backgroundColor:colors.leafSoft},thumbnailImage:{width:'100%',height:'100%'},copy:{flex:1,gap:3},name:{color:colors.ink,fontSize:18,lineHeight:23,fontWeight:'700'},meta:{color:colors.muted,fontSize:14,lineHeight:19},badge:{maxWidth:'31%',color:colors.actionPrimary,fontSize:12,lineHeight:17,fontWeight:'600',textAlign:'right'},pressed:{opacity:.68}});
