import { localizedCatName, catSampleLabel } from '../i18n/cat-name';
import { useEffect, useState, type ReactNode } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { useNativeColors } from '../design/native-colors';
import type { Locale } from '../i18n/catalog';
import { getReportCopy } from '../report/report-copy';
import { AppIcon } from './AppIcon';
import { GlassSurface } from '../design/GlassSurface';
import type { SelectedCatSummary } from './AnchoredCatSheet';

type Props = Readonly<{ children?: ReactNode; heroActions?: ReactNode; cat: SelectedCatSummary; fixture: boolean; locale?: Locale; onBack?: () => void; onReportSighting: (id: string) => void | Promise<void>; onRecordCare?: (id: string) => void | Promise<void> }>;

export function CatDetailScreen({ cat, locale = 'en', onBack, onReportSighting, onRecordCare, children, heroActions }: Props) {
  const colors = useNativeColors(); const styles = makeStyles(colors); const cn = locale === 'zh-CN'; const reportCopy = getReportCopy(locale);
  const [starting, setStarting] = useState(false); const [error, setError] = useState<string | null>(null); const [portraitFailed, setPortraitFailed] = useState(false);
  const portrait = Boolean(cat.portraitUri) && !portraitFailed;
  useEffect(()=>setPortraitFailed(false),[cat.portraitUri]);
  const report = async () => { setStarting(true); setError(null); try { await onReportSighting(cat.animalId); } catch { setError(reportCopy.startFailed); } finally { setStarting(false); } };
  return <SafeAreaView edges={['left','right']} style={styles.screen}>
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.hero}>{portrait ? <Image accessibilityLabel={catSampleLabel(cat.animalId,locale) ?? `${localizedCatName(cat.animalId, cat.primaryAlias, locale)} public portrait`} resizeMode="cover" source={{uri:cat.portraitUri!}} style={styles.heroImage} onError={()=>setPortraitFailed(true)}/> : <View accessibilityLabel={cn?'公开照片不可用':'Public portrait unavailable'} style={styles.heroFallback}><AppIcon name="cat" size={64} color={colors.actionPrimary}/><Text style={styles.fallback}>{cn?'暂无公开照片':'No public photo yet'}</Text></View>}{onBack?<GlassSurface interactive style={styles.back}><Pressable accessibilityRole="button" accessibilityLabel={cn?'返回':'Back'} onPress={onBack} style={styles.backPress}><AppIcon name="back" size={24} color={colors.ink}/></Pressable></GlassSurface>:null}{heroActions?<View style={styles.heroActions}>{heroActions}</View>:null}</View>
      <View style={styles.body}><View style={styles.identity}><View style={styles.copy}><Text accessibilityRole="header" style={styles.name}>{localizedCatName(cat.animalId, cat.primaryAlias, locale)}</Text><Text style={styles.verified}>{cat.verificationLabel}</Text>{catSampleLabel(cat.animalId,locale)?<Text style={styles.verified}>{catSampleLabel(cat.animalId,locale)}</Text>:null}</View></View>
        <View style={styles.facts}><Fact label={cn?'身份状态':'Identity status'} value={cat.verificationLabel} styles={styles}/><Fact label={cn?'粗略社区活动':'Coarse neighbourhood activity'} value={cat.timeLabel} styles={styles}/></View><Text style={styles.protected}>{cn?'这里绝不会显示精确位置、路线或时间戳。':'Exact locations, routes and timestamps stay protected.'}</Text>
        <View style={styles.group}><Pressable accessibilityRole="button" accessibilityLabel={cn?`记录 ${localizedCatName(cat.animalId, cat.primaryAlias, locale)} 的已完成照护`:`Record completed care for ${localizedCatName(cat.animalId, cat.primaryAlias, locale)}`} disabled={!onRecordCare} onPress={()=>{void onRecordCare?.(cat.animalId);}} style={styles.row}><AppIcon name="care" size={23} color={colors.actionPrimary}/><View style={styles.copy}><Text style={styles.rowTitle}>{cn?'照护记录':'Care records'}</Text><Text style={styles.rowNote}>{cn?'查看已完成的照护':'View completed care'}</Text></View><AppIcon name="chevron" size={18} color={colors.muted}/></Pressable></View>{children}{error?<Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text>:null}</View>
    </ScrollView><View style={styles.dock}><Pressable accessibilityRole="button" accessibilityLabel={cn?`报告 ${localizedCatName(cat.animalId, cat.primaryAlias, locale)} 的目击记录`:`Report a sighting of ${localizedCatName(cat.animalId, cat.primaryAlias, locale)}`} disabled={starting} onPress={()=>{void report();}} style={styles.report}><AppIcon name="camera" size={22} color={colors.onAction}/><Text style={styles.reportText}>{cn?'记录目击':'Report a sighting'}</Text></Pressable></View>
  </SafeAreaView>;
}
function Fact({label,value,styles}:{label:string;value:string;styles:ReturnType<typeof makeStyles>}){return <View style={styles.fact}><Text style={styles.factLabel}>{label}</Text><Text style={styles.factValue}>{value}</Text></View>;}
const makeStyles=(colors:ReturnType<typeof useNativeColors>)=>StyleSheet.create({screen:{flex:1,backgroundColor:colors.canvas},content:{paddingBottom:112},hero:{height:356,backgroundColor:colors.leafSoft,overflow:'hidden'},heroImage:{width:'100%',height:'100%'},heroFallback:{flex:1,alignItems:'center',justifyContent:'center',gap:12},fallback:{color:colors.muted,fontSize:15},back:{position:'absolute',top:52,left:20,width:48,height:48,borderRadius:24,overflow:'hidden'},backPress:{width:48,height:48,alignItems:'center',justifyContent:'center'},heroActions:{position:'absolute',top:52,right:20},body:{padding:24,gap:20},identity:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},copy:{flex:1,gap:3},name:{color:colors.ink,fontSize:34,lineHeight:41,fontWeight:'700',letterSpacing:-.5},verified:{color:colors.actionPrimary,fontSize:16,lineHeight:22,fontWeight:'600'},facts:{flexDirection:'row',gap:36},fact:{flex:1,gap:6},factLabel:{color:colors.muted,fontSize:14,lineHeight:19},factValue:{color:colors.ink,fontSize:20,lineHeight:26,fontWeight:'700'},protected:{color:colors.muted,fontSize:14,lineHeight:20},group:{borderRadius:16,backgroundColor:colors.surface,overflow:'hidden'},row:{minHeight:78,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:14},rowTitle:{color:colors.ink,fontSize:17,lineHeight:23,fontWeight:'600'},rowNote:{color:colors.muted,fontSize:14,lineHeight:19},divider:{height:StyleSheet.hairlineWidth,marginLeft:55,backgroundColor:colors.line},error:{color:colors.danger,textAlign:'center'},dock:{paddingHorizontal:20,paddingTop:12,paddingBottom:24,backgroundColor:colors.canvas,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.line},report:{minHeight:54,borderRadius:27,backgroundColor:colors.actionPrimary,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},reportText:{color:colors.onAction,fontSize:17,fontWeight:'700'}});
