import { getSupabaseClient } from './supabase';
import type { CommunityRpcClient } from './community';
import { PROFILE_AVATAR_KEYS } from '../profile/profile-avatar';

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const avatars=new Set<string>(PROFILE_AVATAR_KEYS);
const record=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value);
const uuid=(value:unknown):value is string=>typeof value==='string'&&UUID.test(value);
const time=(value:unknown):value is string=>typeof value==='string'&&Number.isFinite(Date.parse(value));
const member=(value:unknown):value is {name:string;avatarKey:string}=>record(value)&&Object.keys(value).length===2&&typeof value.name==='string'&&value.name.length>0&&value.name.length<=60&&typeof value.avatarKey==='string'&&avatars.has(value.avatarKey);
const body=(value:unknown):value is string=>typeof value==='string'&&value.length>0&&value.length<=2000;

export type DirectConversation=Readonly<{conversationId:string;status:'pending'|'accepted'|'rejected';isIncoming:boolean;otherMember:Readonly<{name:string;avatarKey:string}>;lastMessagePreview:string|null;lastMessageAt:string|null;unreadCount:number;createdAt:string;cursor:string}>;
export type DirectMessage=Readonly<{messageId:string;body:string;sentAt:string;isMine:boolean;requestId:string|null;cursor:string}>;
export interface DirectRpcClient extends CommunityRpcClient {}
function directClient(client?:DirectRpcClient){const rpc=client??getSupabaseClient() as DirectRpcClient|null;if(!rpc)throw new Error('direct_messages_unavailable');return rpc;}
function conversation(value:unknown):value is DirectConversation {return record(value)&&Object.keys(value).length===9&&uuid(value.conversationId)&&['pending','accepted','rejected'].includes(value.status as string)&&typeof value.isIncoming==='boolean'&&member(value.otherMember)&&(value.lastMessagePreview===null||(typeof value.lastMessagePreview==='string'&&value.lastMessagePreview.length<=2000))&&(value.lastMessageAt===null||time(value.lastMessageAt))&&typeof value.unreadCount==='number'&&Number.isInteger(value.unreadCount)&&value.unreadCount>=0&&time(value.createdAt)&&uuid(value.cursor);}
function message(value:unknown):value is DirectMessage{return record(value)&&Object.keys(value).length===6&&uuid(value.messageId)&&body(value.body)&&time(value.sentAt)&&typeof value.isMine==='boolean'&&(value.requestId===null||uuid(value.requestId))&&uuid(value.cursor);}
export function parseDirectConversations(value:unknown){if(!Array.isArray(value)||value.length>20||!value.every(conversation))throw new Error('direct_messages_unavailable');return {items:value as DirectConversation[],nextCursor:value.length===20?value.at(-1)!.cursor:null};}
export async function listDirectConversations(cursor:string|null=null,client?:DirectRpcClient){if(cursor!==null&&!uuid(cursor))throw new Error('direct_messages_unavailable');const {data,error}=await directClient(client).rpc('list_my_direct_conversations',{p_cursor:cursor,p_limit:20});if(error)throw new Error('direct_messages_unavailable');return parseDirectConversations(data);}
export async function getCommunityAuthor(contentType:'community_post'|'community_reply',contentId:string,client?:DirectRpcClient){if(!uuid(contentId))throw new Error('direct_messages_unavailable');const {data,error}=await directClient(client).rpc('get_community_author',{p_content_type:contentType,p_content_id:contentId});if(error||!Array.isArray(data)||data.length!==1||!record(data[0])||Object.keys(data[0]).length!==3||!member(data[0].author)||typeof data[0].canMessage!=='boolean'||(data[0].conversationId!==null&&!uuid(data[0].conversationId)))throw new Error('direct_messages_unavailable');return data[0] as Readonly<{author:{name:string;avatarKey:string};canMessage:boolean;conversationId:string|null}>;}
export async function getDirectConversation(conversationId:string,client?:DirectRpcClient){if(!uuid(conversationId))throw new Error('direct_messages_unavailable');const {data,error}=await directClient(client).rpc('get_direct_conversation',{p_conversation_id:conversationId});if(!error&&Array.isArray(data)&&data.length===0)throw new Error('direct_conversation_hidden');if(error||!Array.isArray(data)||data.length!==1||!conversation(data[0]))throw new Error('direct_messages_unavailable');return data[0] as DirectConversation;}
export async function listDirectMessages(conversationId:string,cursor:string|null=null,client?:DirectRpcClient){if(!uuid(conversationId)||(cursor!==null&&!uuid(cursor)))throw new Error('direct_messages_unavailable');const {data,error}=await directClient(client).rpc('list_direct_messages',{p_conversation_id:conversationId,p_cursor:cursor,p_limit:50});if(error||!Array.isArray(data)||data.length>50||!data.every(message))throw new Error('direct_messages_unavailable');return {items:data as DirectMessage[],nextCursor:data.length===50?data[0]!.cursor:null};}
async function mutation(name:string,args:Record<string,unknown>,valid:(data:unknown)=>boolean,client?:DirectRpcClient){try{const {data,error}=await directClient(client).rpc(name,args);if(error||!Array.isArray(data)||data.length!==1||!valid(data[0]))throw new Error();return data[0];}catch{throw new Error('direct_message_write_failed');}}
export async function createDirectMessageRequest(contentType:'community_post'|'community_reply',contentId:string,text:string,requestId:string,client?:DirectRpcClient){if(!uuid(contentId)||!uuid(requestId)||!body(text))throw new Error('direct_message_write_failed');return mutation('create_direct_message_request',{p_content_type:contentType,p_content_id:contentId,p_body:text,p_request_id:requestId},data=>record(data)&&Object.keys(data).length===4&&uuid(data.conversationId)&&uuid(data.messageId)&&data.status==='pending'&&time(data.createdAt),client) as Promise<Readonly<{conversationId:string;messageId:string;status:'pending';createdAt:string}>>;}
export async function respondToDirectMessageRequest(conversationId:string,accept:boolean,requestId:string,client?:DirectRpcClient){if(!uuid(conversationId)||!uuid(requestId))throw new Error('direct_message_write_failed');return mutation('respond_direct_message_request',{p_conversation_id:conversationId,p_accept:accept,p_request_id:requestId},data=>record(data)&&Object.keys(data).length===3&&uuid(data.conversationId)&&['accepted','rejected'].includes(data.status as string)&&time(data.updatedAt),client) as Promise<Readonly<{conversationId:string;status:'accepted'|'rejected';updatedAt:string}>>;}
export async function sendDirectMessage(conversationId:string,text:string,requestId:string,client?:DirectRpcClient){if(!uuid(conversationId)||!uuid(requestId)||!body(text))throw new Error('direct_message_write_failed');return mutation('send_direct_message',{p_conversation_id:conversationId,p_body:text,p_request_id:requestId},data=>record(data)&&Object.keys(data).length===3&&uuid(data.conversationId)&&uuid(data.messageId)&&time(data.sentAt),client) as Promise<Readonly<{conversationId:string;messageId:string;sentAt:string}>>;}
export async function markDirectConversationRead(conversationId:string,messageId:string,client?:DirectRpcClient){if(!uuid(conversationId)||!uuid(messageId))throw new Error('direct_message_write_failed');await mutation('mark_direct_conversation_read',{p_conversation_id:conversationId,p_message_id:messageId},data=>record(data)&&Object.keys(data).length===3&&uuid(data.conversationId)&&uuid(data.messageId)&&time(data.readAt),client);}
export async function blockDirectConversation(conversationId:string,requestId:string,client?:DirectRpcClient){if(!uuid(conversationId)||!uuid(requestId))throw new Error('direct_message_write_failed');try{const {data,error}=await directClient(client).rpc('block_direct_conversation',{p_conversation_id:conversationId,p_request_id:requestId});if(error||!uuid(data))throw new Error();}catch{throw new Error('direct_message_write_failed');}}
