import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { listMyCommunityActivity, markCommunityActivityRead, type CommunityActivity } from '../api/community-activity';
import { useAccountSession } from '../auth/use-account-session';
import { AppIcon } from '../components/AppIcon';
import { useNativeColors } from '../design/native-colors';
import { useLocale } from '../i18n/LocaleContext';

export function ActivityInbox(){
 const {locale}=useLocale(),cn=locale==='zh-CN',c=useNativeColors(),router=useRouter(),auth=useAccountSession();const [items,setItems]=useState<readonly CommunityActivity[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[failed,setFailed]=useState(false);const busy=useRef(false),epoch=useRef(0);
 const load=useCallback(async(refresh=false)=>{if(busy.current||auth.owner===undefined)return;busy.current=true;const token=++epoch.current,current=auth.pin();if(refresh)setRefreshing(true);else setLoading(true);setFailed(false);try{const page=await listMyCommunityActivity();if(token===epoch.current&&await current())setItems(page.items);}catch{if(token===epoch.current&&await current())setFailed(true);}finally{busy.current=false;if(token===epoch.current){setLoading(false);setRefreshing(false);}}},[auth.owner,auth.pin]);
 useEffect(()=>{epoch.current++;setItems([]);if(auth.owner!==undefined)void load();},[auth.owner,load]);
 const open=async(item:CommunityActivity)=>{try{if(!item.readAt)await markCommunityActivityRead([item.eventId]);}catch{}setItems(old=>old.map(value=>value.eventId===item.eventId?{...value,readAt:new Date().toISOString()}:value));router.push(`/community/${item.postId}` as never);};
 return <View style={styles.wrap}><View style={styles.heading}><Text accessibilityRole="header" style={[styles.title,{color:c.ink}]}>{cn?'互动':'Activity'}</Text><Pressable accessibilityRole="button" accessibilityLabel={cn?'刷新互动':'Refresh activity'} onPress={()=>void load(true)} style={styles.icon}><AppIcon name="activity" color={c.actionPrimary}/></Pressable></View><Text style={[styles.copy,{color:c.muted}]}>{cn?'来自真实评论和点赞':'Real comments and likes'}</Text>{loading&&!items.length?<ActivityIndicator color={c.actionPrimary}/>:null}{failed?<Pressable accessibilityRole="button" onPress={()=>void load(true)}><Text style={{color:c.actionPrimary}}>{cn?'互动暂不可用，点此重试':'Activity unavailable. Tap to retry.'}</Text></Pressable>:null}<ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)}/>} contentContainerStyle={styles.list}>{!loading&&!failed&&!items.length?<Text style={{color:c.muted}}>{cn?'还没有真实互动。':'No activity yet.'}</Text>:null}{items.map(item=><Pressable key={item.eventId} accessibilityRole="button" onPress={()=>void open(item)} style={[styles.row,!item.readAt&&{backgroundColor:c.leafSoft}]}><AppIcon name={item.kind==='like'?'heart':'reply'} color={c.actionPrimary}/><View style={{flex:1}}><Text style={{color:c.ink,fontWeight:'600'}}>{item.actor.name} {item.kind==='like'?(cn?'赞了你的帖子':'liked your post'):(cn?'评论了你的帖子':'commented on your post')}</Text><Text style={{color:c.muted,fontSize:13}}>{new Date(item.createdAt).toLocaleDateString(cn?'zh-SG':'en-SG',{month:'short',day:'numeric'})}</Text></View><AppIcon name="chevron" size={16} color={c.muted}/></Pressable>)}</ScrollView></View>;
}
const styles=StyleSheet.create({wrap:{flex:1,padding:16,gap:8},heading:{flexDirection:'row',alignItems:'center'},title:{flex:1,fontSize:22,fontWeight:'700'},copy:{fontSize:14},icon:{width:44,height:44,alignItems:'center',justifyContent:'center'},list:{paddingTop:8,gap:8},row:{minHeight:64,borderRadius:16,padding:12,flexDirection:'row',alignItems:'center',gap:12}});
