import {useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Pressable,StyleSheet,Text,View} from 'react-native';
import {useRouter} from 'expo-router';
import {listDirectConversations,type DirectConversation} from '../api/direct-messages';
import {useAccountSession} from '../auth/use-account-session';
import {CommunityAuthorAvatar} from './CommunityAuthorAvatar';
import {AppIcon} from '../components/AppIcon';
import {ScreenScaffold} from '../components/ScreenScaffold';
import {useNativeColors} from '../design/native-colors';
import {useLocale} from '../i18n/LocaleContext';

const merge=(old:readonly DirectConversation[],next:readonly DirectConversation[])=>[...new Map([...old,...next].map(x=>[x.conversationId,x])).values()].sort((a,b)=>Date.parse(b.lastMessageAt??b.createdAt)-Date.parse(a.lastMessageAt??a.createdAt));
export function MessagesInbox(){const {locale}=useLocale(),cn=locale==='zh-CN',auth=useAccountSession(),router=useRouter(),c=useNativeColors();const [items,setItems]=useState<readonly DirectConversation[]>([]),[cursor,setCursor]=useState<string|null>(null),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false);const token=useRef(0);
 const load=useCallback(async(more=false)=>{if(!auth.owner||(more&&!cursor))return;const t=++token.current,pin=auth.pin();setLoading(!more);try{const page=await listDirectConversations(more?cursor:null);if(t===token.current&&await pin()){setItems(old=>more?merge(old,page.items):page.items);setCursor(page.nextCursor);setFailed(false);}}catch{if(t===token.current&&await pin())setFailed(true);}finally{if(t===token.current&&await pin())setLoading(false);}},[auth.owner,auth.pin,cursor]);
 useEffect(()=>{token.current++;setItems([]);setCursor(null);setFailed(false);if(auth.owner)void load();else setLoading(auth.owner===undefined);},[auth.owner]);
 if(auth.owner===null)return <ScreenScaffold compact title={cn?'消息':'Messages'}><View style={s.empty}><Text style={{color:c.muted}}>{cn?'登录后查看私信和互动。':'Sign in to see messages and activity.'}</Text><Pressable accessibilityRole="button" onPress={()=>router.push('/profile' as never)} style={s.touch}><Text style={{color:c.actionPrimary}}>{cn?'登录':'Sign in'}</Text></Pressable></View></ScreenScaffold>;
 return <ScreenScaffold compact title={cn?'消息':'Messages'} onRefresh={()=>void load()} refreshing={loading&&items.length>0} refreshLabel={cn?'刷新消息':'Refresh messages'}><View style={s.shortcuts}><Pressable accessibilityRole="button" accessibilityLabel={cn?'互动':'Activity'} onPress={()=>router.push('/activity' as never)} style={[s.shortcut,{backgroundColor:c.surface}]}><AppIcon name="activity" color={c.actionPrimary}/><Text style={{color:c.ink,fontWeight:'600'}}>{cn?'互动':'Activity'}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={cn?'消息请求':'Message requests'} onPress={()=>router.push('/requests' as never)} style={[s.shortcut,{backgroundColor:c.surface}]}><AppIcon name="mail" color={c.actionPrimary}/><Text style={{color:c.ink,fontWeight:'600'}}>{cn?'消息请求':'Requests'}</Text></Pressable></View>{loading&&!items.length?<ActivityIndicator color={c.actionPrimary}/>:null}{failed?<Pressable accessibilityRole="button" onPress={()=>void load()} style={s.touch}><Text style={{color:c.actionPrimary}}>{cn?'消息暂不可用，点此重试。':'Messages unavailable. Tap to retry.'}</Text></Pressable>:null}{items.map(row=><Pressable key={row.conversationId} accessibilityRole="button" onPress={()=>router.push(`/messages/${row.conversationId}` as never)} style={s.row}><CommunityAuthorAvatar id={row.conversationId} avatarKey={row.otherMember.avatarKey} size={44}/><View style={{flex:1,gap:2}}><View style={{flexDirection:'row',justifyContent:'space-between',gap:8}}><Text style={{color:c.ink,fontWeight:'600'}}>{row.otherMember.name}</Text><Text style={{color:c.muted,fontSize:12}}>{new Date(row.lastMessageAt??row.createdAt).toLocaleDateString(cn?'zh-SG':'en-SG',{month:'short',day:'numeric'})}</Text></View><Text numberOfLines={1} style={{color:c.muted}}>{row.status==='pending'?(row.isIncoming?(cn?'等待你的回复':'Awaiting your response'):(cn?'已发送请求':'Request sent')):row.lastMessagePreview??(cn?'开始对话':'Start a conversation')}</Text></View>{row.unreadCount>0?<View accessibilityLabel={cn?'未读消息':'Unread messages'} style={[s.dot,{backgroundColor:c.actionPrimary}]}><Text style={{color:c.onAction,fontSize:11}}>{row.unreadCount>9?'9+':row.unreadCount}</Text></View>:null}</Pressable>)}{!loading&&!failed&&!items.length?<View style={s.empty}><Text style={{color:c.muted}}>{cn?'还没有消息。':'No messages yet.'}</Text></View>:null}{cursor?<Pressable accessibilityRole="button" onPress={()=>void load(true)} style={s.touch}><Text style={{color:c.actionPrimary}}>{cn?'载入更多':'Load more'}</Text></Pressable>:null}</ScreenScaffold>;}
const s=StyleSheet.create({shortcuts:{flexDirection:'row',gap:10},shortcut:{minHeight:76,borderRadius:18,padding:12,flex:1,gap:6},row:{minHeight:72,paddingVertical:12,flexDirection:'row',gap:12,alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderColor:'rgba(20,50,60,.12)'},dot:{minWidth:20,height:20,borderRadius:10,alignItems:'center',justifyContent:'center',paddingHorizontal:4},touch:{minHeight:44,justifyContent:'center',alignSelf:'flex-start'},empty:{paddingVertical:32,alignItems:'center',gap:10}});
