"""Generate a compact, attributed URA planning-area bundle from the official GeoJSON.
Usage: python scripts/build-singapore-geography.py downloaded.geojson
No network/credentials required. Coordinates are planning boundaries, not cat positions.
"""
import hashlib
import json
import sys
from pathlib import Path

def simplify(points, tolerance=0.00015):
    if len(points) <= 2:
        return points
    a, b = points[0], points[-1]
    dx, dy = b[0]-a[0], b[1]-a[1]
    denom = dx*dx+dy*dy
    distances = []
    for x, y, *_ in points[1:-1]:
        t = max(0, min(1, ((x-a[0])*dx+(y-a[1])*dy)/denom)) if denom else 0
        distances.append((x-a[0]-t*dx)**2+(y-a[1]-t*dy)**2)
    greatest = max(distances, default=0)
    if greatest <= tolerance*tolerance:
        return [a,b]
    i = distances.index(greatest)+1
    return simplify(points[:i+1],tolerance)[:-1]+simplify(points[i:],tolerance)

source = Path(sys.argv[1]).read_bytes()
features = json.loads(source)['features']
regions = {'CR':'central','ER':'east','NER':'north_east','NR':'north','WR':'west'}
areas = []
for feature in features:
    props, geometry = feature['properties'], feature['geometry']
    polygons = geometry['coordinates'] if geometry['type']=='MultiPolygon' else [geometry['coordinates']]
    compact = []
    for polygon in polygons:
        rings = []
        for ring in polygon:
            short = simplify(ring)
            if len(short)<4:
                short=ring
            rings.append([[round(p[0],5),round(p[1],5)] for p in short])
        compact.append(rings)
    outer = max(compact,key=lambda polygon: len(polygon[0]))[0]
    # A camera centre, never asserted as an observation location.
    center = [round(sum(p[i] for p in outer[:-1])/(len(outer)-1),5) for i in (0,1)]
    name = props['PLN_AREA_N'].title()
    areas.append(dict(id=props['PLN_AREA_N'].lower().replace(' ','-'),name=name,code=props['PLN_AREA_C'],region=regions[props['REGION_C']],center=center,polygons=compact))
areas.sort(key=lambda area: area['name'])
target = Path(__file__).resolve().parents[1]/'packages/domain/src/singapore-geography-data.ts'
target.write_text('// Generated by scripts/build-singapore-geography.py. URA Master Plan 2025, Singapore Open Data Licence.\n// Source SHA256: '+hashlib.sha256(source).hexdigest()+'\nexport const singaporeGeographyData = '+json.dumps(areas,separators=(',',':'))+';\n',encoding='utf-8')
print(f'Generated {len(areas)} planning areas; {target.stat().st_size} bytes')
