"""Build the offline subzone layer from URA MP2019 GeoJSON (not MP2025).
Usage: python scripts/build-singapore-neighbourhoods.py downloaded.geojson
Public planning boundaries only; never observation coordinates.
"""
import hashlib
import json
import sys
from pathlib import Path

def simplify(points, tolerance=0.00010):
    if len(points) <= 2:
        return points
    a, b = points[0], points[-1]
    dx, dy = b[0]-a[0], b[1]-a[1]
    denom = dx*dx+dy*dy
    distances = []
    for x, y, *_ in points[1:-1]:
        t = max(0, min(1, ((x-a[0])*dx+(y-a[1])*dy)/denom)) if denom else 0
        distances.append((x-a[0]-t*dx)**2+(y-a[1]-t*dy)**2)
    if max(distances, default=0) <= tolerance*tolerance:
        return [a,b]
    i = distances.index(max(distances))+1
    return simplify(points[:i+1],tolerance)[:-1]+simplify(points[i:],tolerance)

def interior_point(polygons):
    # An even/odd scanline includes holes and concavities. Pick the widest land
    # interval in the largest polygon instead of averaging vertices over water.
    def area(polygon):
        ring=polygon[0]
        return abs(sum(a[0]*b[1]-b[0]*a[1] for a,b in zip(ring,ring[1:])))
    polygon=max(polygons,key=area)
    heights=sorted(set(p[1] for ring in polygon for p in ring))
    candidates=[]
    for lower,upper in zip(heights,heights[1:]):
        y=(lower+upper)/2
        crossings=[]
        for ring in polygon:
            for a,b in zip(ring,ring[1:]):
                if (a[1]>y)!=(b[1]>y):
                    crossings.append(a[0]+(y-a[1])*(b[0]-a[0])/(b[1]-a[1]))
        crossings.sort()
        for left,right in zip(crossings[::2],crossings[1::2]):
            candidates.append((right-left,[(left+right)/2,y]))
    if not candidates:
        raise ValueError('Subzone has no interior; check source geometry')
    return max(candidates,key=lambda item:item[0])[1]

source = Path(sys.argv[1]).read_bytes()
areas = []
for feature in json.loads(source)['features']:
    props, geometry = feature['properties'], feature['geometry']
    polygons = geometry['coordinates'] if geometry['type']=='MultiPolygon' else [geometry['coordinates']]
    compact = []
    for polygon in polygons:
        rings = []
        for ring in polygon:
            short = simplify(ring)
            if len(short)<4:
                short=ring
            rings.append([[round(p[0],5),round(p[1],5)] for p in short])
        compact.append(rings)
    center = interior_point(compact)
    areas.append(dict(id='sg-'+props['SUBZONE_C'].lower(),name=props['SUBZONE_N'].title(),code=props['SUBZONE_C'],parentId=props['PLN_AREA_N'].lower().replace(' ','-'),center=center,polygons=compact))
areas.sort(key=lambda area: (area['parentId'],area['name']))
target = Path(__file__).resolve().parents[1]/'packages/domain/src/singapore-neighbourhood-data.ts'
target.write_text('// Generated by scripts/build-singapore-neighbourhoods.py. URA Master Plan 2019, Singapore Open Data Licence.\n// https://data.gov.sg/datasets/d_8594ae9ff96d0c708bc2af633048edfb/view\n// Source SHA256: '+hashlib.sha256(source).hexdigest()+'\nexport const singaporeNeighbourhoodData = '+json.dumps(areas,separators=(',',':'))+';\n',encoding='utf-8')
print(f'Generated {len(areas)} subzones; {target.stat().st_size} bytes')
