begin;

alter table private.direct_message_requests add column result_status text check(result_status is null or result_status in ('pending','accepted','rejected'));
alter table private.direct_message_requests add column result_updated_at timestamptz;

create or replace function private.community_reply_available(p_reply_id uuid,p_actor uuid) returns boolean language sql stable security definer set search_path=pg_catalog as $$
 select exists(select 1 from public.community_replies r left join public.community_replies parent on parent.id=r.parent_reply_id where r.id=p_reply_id and r.deleted_at is null and r.moderation_hidden_at is null and private.community_post_available(r.post_id,p_actor) and (r.parent_reply_id is null or (parent.id is not null and parent.deleted_at is null and parent.moderation_hidden_at is null and (p_actor is null or parent.author_id is null or not exists(select 1 from public.user_blocks b where (b.blocker_id=p_actor and b.blocked_id=parent.author_id) or (b.blocker_id=parent.author_id and b.blocked_id=p_actor))))) and (p_actor is null or r.author_id is null or not exists(select 1 from public.user_blocks b where (b.blocker_id=p_actor and b.blocked_id=r.author_id) or (b.blocker_id=r.author_id and b.blocked_id=p_actor))));
$$;
create or replace function private.community_target_available(p_type text,p_id uuid,p_actor uuid) returns table(author_id uuid) language sql stable security definer set search_path=pg_catalog as $$
 select p.author_id from public.community_posts p where p_type='community_post' and p.id=p_id and private.community_post_available(p.id,p_actor)
 union all select r.author_id from public.community_replies r where p_type='community_reply' and r.id=p_id and private.community_reply_available(r.id,p_actor);
$$;
create or replace function public.list_public_community_replies(p_post_id uuid,p_cursor uuid default null,p_limit integer default 30) returns table("replyId" uuid,body text,"createdAt" timestamptz,author jsonb,"canDelete" boolean,cursor uuid) language plpgsql stable security definer set search_path=pg_catalog as $$
declare v_actor uuid:=auth.uid(); v_created timestamptz; v_id uuid;
begin
 if not private.community_post_available(p_post_id,v_actor) then raise exception 'community_post_not_available' using errcode='P0001'; end if;
 if p_cursor is not null then select r.created_at,r.id into v_created,v_id from public.community_replies r where r.id=p_cursor and r.post_id=p_post_id and r.parent_reply_id is null and private.community_reply_available(r.id,v_actor); if not found then raise exception 'invalid_community_cursor' using errcode='P0001'; end if; end if;
 return query select r.id,r.body,r.created_at,jsonb_build_object('name',coalesce(profile.public_name,'Community member'),'avatarKey',coalesce(profile.avatar_key,'person')),coalesce(v_actor is not null and r.author_id=v_actor,false),r.id from public.community_replies r left join public.user_profiles profile on profile.id=r.author_id where r.post_id=p_post_id and r.parent_reply_id is null and private.community_reply_available(r.id,v_actor) and (p_cursor is null or (r.created_at,r.id)>(v_created,v_id)) order by r.created_at,r.id limit least(greatest(coalesce(p_limit,30),1),50);
end $$;
create or replace function public.list_my_community_activity(p_cursor uuid default null,p_limit integer default 20) returns table("eventId" uuid,kind text,"postId" uuid,"replyId" uuid,actor jsonb,"createdAt" timestamptz,"readAt" timestamptz,cursor uuid) language plpgsql stable security definer set search_path=pg_catalog as $$
declare recipient uuid:=auth.uid(); cursor_created timestamptz; cursor_id uuid;
begin
 if recipient is null then raise exception 'authentication_required' using errcode='42501'; end if; if p_limit is null or p_limit not between 1 and 50 then raise exception 'invalid_community_activity_limit' using errcode='22023'; end if;
 if p_cursor is not null then select event.created_at,event.id into cursor_created,cursor_id from private.community_activity event where event.id=p_cursor and event.recipient_id=recipient and private.community_activity_available(event.id,recipient); if not found then raise exception 'invalid_community_activity_cursor' using errcode='P0001'; end if; end if;
 return query select event.id,case when event.kind='comment_reply' then 'comment' else event.kind end,event.post_id,event.reply_id,jsonb_build_object('name',coalesce(profile.public_name,'Community member'),'avatarKey',coalesce(profile.avatar_key,'person')),event.created_at,event.read_at,event.id from private.community_activity event join public.user_profiles profile on profile.id=event.actor_id where event.recipient_id=recipient and private.community_activity_available(event.id,recipient) and (p_cursor is null or (event.created_at,event.id)<(cursor_created,cursor_id)) order by event.created_at desc,event.id desc limit p_limit;
end $$;

create or replace function public.get_community_author(p_content_type text,p_content_id uuid) returns table(author jsonb,"canMessage" boolean,"conversationId" uuid) language plpgsql stable security definer set search_path=pg_catalog as $$
declare v_actor uuid:=auth.uid(); v_author uuid; v_conversation uuid;
begin
 select author_id into v_author from private.community_target_available(p_content_type,p_content_id,v_actor); if not found then return; end if;
 if v_actor is not null and v_author is not null and v_author<>v_actor then select c.id into v_conversation from private.direct_conversations c where c.member_low_id=least(v_actor,v_author) and c.member_high_id=greatest(v_actor,v_author) and private.direct_conversation_available(c.id,v_actor); end if;
 return query select jsonb_build_object('name',coalesce(profile.public_name,'Community member'),'avatarKey',coalesce(profile.avatar_key,'person')),coalesce(v_conversation is null and v_actor is not null and v_author is not null and v_author<>v_actor and not exists(select 1 from private.account_erasure_requests e where e.target_subject_id in (v_actor,v_author) and e.status<>'completed') and not exists(select 1 from public.user_blocks b where (b.blocker_id=v_actor and b.blocked_id=v_author) or (b.blocker_id=v_author and b.blocked_id=v_actor)),false),v_conversation from (select 1) anchor left join public.user_profiles profile on profile.id=v_author;
end $$;

create or replace function public.create_direct_message_request(p_content_type text,p_content_id uuid,p_body text,p_request_id uuid) returns table("conversationId" uuid,"messageId" uuid,status text,"createdAt" timestamptz) language plpgsql volatile security definer set search_path=pg_catalog as $$
declare v_actor uuid:=auth.uid(); v_target uuid; v_body text:=nullif(btrim(p_body),''); v_hash text; v_prior private.direct_message_requests%rowtype; v_conversation private.direct_conversations%rowtype; v_message private.direct_messages%rowtype;
begin
 if v_actor is null then raise exception 'authentication_required' using errcode='42501'; end if; if v_body is null or char_length(v_body)>2000 or p_request_id is null then raise exception 'invalid_direct_message_request' using errcode='22023'; end if;
 select author_id into v_target from private.community_target_available(p_content_type,p_content_id,v_actor); if not found or v_target is null or v_target=v_actor or exists(select 1 from private.account_erasure_requests e where e.target_subject_id in (v_actor,v_target) and e.status<>'completed') then raise exception 'direct_message_target_not_available' using errcode='P0001'; end if;
 v_hash:=encode(extensions.digest(jsonb_build_object('contentType',p_content_type,'contentId',p_content_id,'body',v_body)::text,'sha256'),'hex'); perform private.lock_direct_lifecycle(); select author_id into v_target from private.community_target_available(p_content_type,p_content_id,v_actor); if not found or v_target is null or v_target=v_actor or exists(select 1 from private.account_erasure_requests e where e.target_subject_id in (v_actor,v_target) and e.status<>'completed') then raise exception 'direct_message_target_not_available' using errcode='P0001'; end if; perform pg_advisory_xact_lock(hashtextextended('direct_message_request:'||v_actor::text||':'||p_request_id::text,0)); select * into v_prior from private.direct_message_requests where actor_id=v_actor and request_id=p_request_id for update;
 if found then if v_prior.operation<>'request' or v_prior.payload_hash<>v_hash then raise exception 'idempotency_conflict' using errcode='P0001'; end if; select * into v_conversation from private.direct_conversations where id=v_prior.result_conversation_id; select * into v_message from private.direct_messages where id=v_prior.result_message_id; if not found or not private.direct_conversation_available(v_conversation.id,v_actor) then raise exception 'direct_message_not_available' using errcode='P0001'; end if; return query select v_conversation.id,v_message.id,coalesce(v_prior.result_status,'pending'),v_message.created_at; return; end if;
 select * into v_conversation from private.direct_conversations where member_low_id=least(v_actor,v_target) and member_high_id=greatest(v_actor,v_target) for update; if found then raise exception 'direct_message_request_not_available' using errcode='P0001'; end if;
 insert into private.direct_conversations(member_low_id,member_high_id,requested_by,status) values(least(v_actor,v_target),greatest(v_actor,v_target),v_actor,'pending') returning * into v_conversation; insert into private.direct_conversation_members(conversation_id,member_id) values(v_conversation.id,v_actor),(v_conversation.id,v_target); insert into private.direct_messages(conversation_id,sender_id,body,request_id) values(v_conversation.id,v_actor,v_body,p_request_id) returning * into v_message; insert into private.direct_message_requests(actor_id,request_id,operation,payload_hash,result_conversation_id,result_message_id,result_status) values(v_actor,p_request_id,'request',v_hash,v_conversation.id,v_message.id,'pending'); return query select v_conversation.id,v_message.id,'pending'::text,v_message.created_at;
end $$;

create or replace function public.respond_direct_message_request(p_conversation_id uuid,p_accept boolean,p_request_id uuid) returns table("conversationId" uuid,status text,"updatedAt" timestamptz) language plpgsql volatile security definer set search_path=pg_catalog as $$
declare v_actor uuid:=auth.uid(); v_hash text; v_prior private.direct_message_requests%rowtype; v_conversation private.direct_conversations%rowtype;
begin
 if v_actor is null then raise exception 'authentication_required' using errcode='42501'; end if; if p_conversation_id is null or p_accept is null or p_request_id is null then raise exception 'invalid_direct_message_response' using errcode='22023'; end if; select * into v_conversation from private.direct_conversations where id=p_conversation_id and (member_low_id=v_actor or member_high_id=v_actor); if not found then raise exception 'direct_message_request_not_available' using errcode='P0001'; end if; perform private.lock_direct_lifecycle(); if not private.direct_conversation_available(p_conversation_id,v_actor) then raise exception 'direct_message_request_not_available' using errcode='P0001'; end if;
 v_hash:=encode(extensions.digest(jsonb_build_object('conversationId',p_conversation_id,'accept',p_accept)::text,'sha256'),'hex'); perform pg_advisory_xact_lock(hashtextextended('direct_message_request:'||v_actor::text||':'||p_request_id::text,0)); select * into v_prior from private.direct_message_requests where actor_id=v_actor and request_id=p_request_id for update;
 if found then if v_prior.operation<>'respond' or v_prior.payload_hash<>v_hash then raise exception 'idempotency_conflict' using errcode='P0001'; end if; select * into v_conversation from private.direct_conversations where id=v_prior.result_conversation_id; if not found or not private.direct_conversation_available(v_conversation.id,v_actor) then raise exception 'direct_message_request_not_available' using errcode='P0001'; end if; return query select v_conversation.id,coalesce(v_prior.result_status,v_conversation.status),coalesce(v_prior.result_updated_at,v_conversation.updated_at); return; end if;
 select * into v_conversation from private.direct_conversations where id=p_conversation_id for update; if not found or v_conversation.status<>'pending' or v_conversation.requested_by=v_actor then raise exception 'direct_message_request_not_available' using errcode='P0001'; end if; update private.direct_conversations set status=case when p_accept then 'accepted' else 'rejected' end,updated_at=now() where id=p_conversation_id returning * into v_conversation; insert into private.direct_message_requests(actor_id,request_id,operation,payload_hash,result_conversation_id,result_status,result_updated_at) values(v_actor,p_request_id,'respond',v_hash,v_conversation.id,v_conversation.status,v_conversation.updated_at); return query select v_conversation.id,v_conversation.status,v_conversation.updated_at;
end $$;

create or replace function public.send_direct_message(p_conversation_id uuid,p_body text,p_request_id uuid) returns table("conversationId" uuid,"messageId" uuid,"sentAt" timestamptz) language plpgsql volatile security definer set search_path=pg_catalog as $$
declare v_actor uuid:=auth.uid(); v_body text:=nullif(btrim(p_body),''); v_hash text; v_prior private.direct_message_requests%rowtype; v_conversation private.direct_conversations%rowtype; v_message private.direct_messages%rowtype;
begin
 if v_actor is null then raise exception 'authentication_required' using errcode='42501'; end if; if p_conversation_id is null or v_body is null or char_length(v_body)>2000 or p_request_id is null then raise exception 'invalid_direct_message' using errcode='22023'; end if; select * into v_conversation from private.direct_conversations where id=p_conversation_id and (member_low_id=v_actor or member_high_id=v_actor); if not found then raise exception 'direct_message_not_available' using errcode='P0001'; end if; perform private.lock_direct_lifecycle(); if not private.direct_conversation_available(p_conversation_id,v_actor) then raise exception 'direct_message_not_available' using errcode='P0001'; end if;
 v_hash:=encode(extensions.digest(jsonb_build_object('conversationId',p_conversation_id,'body',v_body)::text,'sha256'),'hex'); perform pg_advisory_xact_lock(hashtextextended('direct_message_request:'||v_actor::text||':'||p_request_id::text,0)); select * into v_prior from private.direct_message_requests where actor_id=v_actor and request_id=p_request_id for update; if found then if v_prior.operation<>'send' or v_prior.payload_hash<>v_hash then raise exception 'idempotency_conflict' using errcode='P0001'; end if; select * into v_message from private.direct_messages where id=v_prior.result_message_id; if not found then raise exception 'direct_message_not_available' using errcode='P0001'; end if; return query select v_prior.result_conversation_id,v_message.id,v_message.created_at; return; end if;
 select * into v_conversation from private.direct_conversations where id=p_conversation_id for update; if not found or v_conversation.status<>'accepted' then raise exception 'direct_message_not_available' using errcode='P0001'; end if; insert into private.direct_messages(conversation_id,sender_id,body,request_id) values(p_conversation_id,v_actor,v_body,p_request_id) returning * into v_message; update private.direct_conversations set updated_at=v_message.created_at where id=p_conversation_id; insert into private.direct_message_requests(actor_id,request_id,operation,payload_hash,result_conversation_id,result_message_id) values(v_actor,p_request_id,'send',v_hash,p_conversation_id,v_message.id); return query select p_conversation_id,v_message.id,v_message.created_at;
end $$;

create or replace function public.mark_direct_conversation_read(p_conversation_id uuid,p_message_id uuid) returns table("conversationId" uuid,"readAt" timestamptz,"messageId" uuid) language plpgsql volatile security definer set search_path=pg_catalog as $$
declare v_actor uuid:=auth.uid(); v_message private.direct_messages%rowtype; v_read_at timestamptz;
begin
 if v_actor is null then raise exception 'authentication_required' using errcode='42501'; end if; if not private.direct_conversation_available(p_conversation_id,v_actor) then raise exception 'direct_message_not_available' using errcode='P0001'; end if; select * into v_message from private.direct_messages where id=p_message_id and conversation_id=p_conversation_id; if not found then raise exception 'direct_message_not_available' using errcode='P0001'; end if;
 update private.direct_conversation_members member set last_read_message_id=case when member.last_read_message_id is null or (v_message.created_at,v_message.id)>(coalesce((select old.created_at from private.direct_messages old where old.id=member.last_read_message_id),'epoch'::timestamptz),member.last_read_message_id) then v_message.id else member.last_read_message_id end,last_read_at=greatest(coalesce(member.last_read_at,'epoch'::timestamptz),v_message.created_at) where member.conversation_id=p_conversation_id and member.member_id=v_actor returning member.last_read_at into v_read_at; return query select p_conversation_id,v_read_at,v_message.id;
end $$;

create or replace function public.list_my_direct_conversations(p_cursor uuid default null,p_limit integer default 20) returns table("conversationId" uuid,status text,"isIncoming" boolean,"otherMember" jsonb,"lastMessagePreview" text,"lastMessageAt" timestamptz,"unreadCount" integer,"createdAt" timestamptz,cursor uuid) language plpgsql stable security definer set search_path=pg_catalog as $$
declare v_actor uuid:=auth.uid(); v_created timestamptz; v_id uuid;
begin
 if v_actor is null then raise exception 'authentication_required' using errcode='42501'; end if; if p_limit is null or p_limit not between 1 and 50 then raise exception 'invalid_direct_message_limit' using errcode='22023'; end if; if p_cursor is not null then select c.updated_at,c.id into v_created,v_id from private.direct_conversations c where c.id=p_cursor and private.direct_conversation_available(c.id,v_actor); if not found then raise exception 'invalid_direct_message_cursor' using errcode='P0001'; end if; end if;
 return query select c.id,c.status,c.requested_by<>v_actor,jsonb_build_object('name',coalesce(profile.public_name,'Community member'),'avatarKey',coalesce(profile.avatar_key,'person')),last_message.body,last_message.created_at,(select count(*)::integer from private.direct_messages unread where unread.conversation_id=c.id and unread.sender_id<>v_actor and (member.last_read_message_id is null or (unread.created_at,unread.id)>(coalesce((select read_message.created_at from private.direct_messages read_message where read_message.id=member.last_read_message_id),'epoch'::timestamptz),member.last_read_message_id))),c.created_at,c.id from private.direct_conversations c join private.direct_conversation_members member on member.conversation_id=c.id and member.member_id=v_actor join public.user_profiles profile on profile.id=case when c.member_low_id=v_actor then c.member_high_id else c.member_low_id end left join lateral(select m.body,m.created_at from private.direct_messages m where m.conversation_id=c.id order by m.created_at desc,m.id desc limit 1) last_message on true where private.direct_conversation_available(c.id,v_actor) and (p_cursor is null or (c.updated_at,c.id)<(v_created,v_id)) order by c.updated_at desc,c.id desc limit p_limit;
end $$;

create or replace function private.can_read_profile_avatar(p_bucket text,p_name text,p_actor uuid) returns boolean language sql stable security definer set search_path=pg_catalog as $$
 select p_bucket='profile-avatars' and exists(select 1 from public.user_profiles profile join private.profile_avatar_upload_jobs job on job.object_path=profile.avatar_object_path where profile.avatar_object_path=p_name and job.owner_id=profile.id and job.status='finalized' and (p_actor=profile.id or exists(select 1 from public.community_posts post where post.author_id=profile.id and private.community_post_available(post.id,p_actor)) or exists(select 1 from public.community_replies reply where reply.author_id=profile.id and private.community_reply_available(reply.id,p_actor))));
$$;
create or replace function public.list_public_community_posts(p_cursor uuid default null,p_limit integer default 20,p_community_slug text default null,p_cat_id uuid default null) returns table("postId" uuid,body text,"catId" uuid,"communitySlug" text,"createdAt" timestamptz,author jsonb,"replyCount" integer,"canDelete" boolean,cursor uuid) language plpgsql stable security definer set search_path=pg_catalog as $$
declare v_actor uuid:=auth.uid(); v_created timestamptz; v_id uuid;
begin
 if p_community_slug is not null and p_community_slug !~ '^[a-z0-9][a-z0-9-]{0,79}$' then raise exception 'invalid_community_scope' using errcode='22023'; end if; if p_cursor is not null then select p.created_at,p.id into v_created,v_id from public.community_posts p where p.id=p_cursor and private.community_post_available(p.id,v_actor); if not found then raise exception 'invalid_community_cursor' using errcode='P0001'; end if; end if;
 return query select p.id,p.body,p.cat_id,p.community_slug,p.created_at,jsonb_build_object('name',coalesce(profile.public_name,'Community member'),'avatarKey',coalesce(profile.avatar_key,'person')),(select count(*)::integer from public.community_replies r where r.post_id=p.id and r.parent_reply_id is null and private.community_reply_available(r.id,v_actor)),coalesce(v_actor is not null and p.author_id=v_actor,false),p.id from public.community_posts p left join public.user_profiles profile on profile.id=p.author_id where private.community_post_available(p.id,v_actor) and (p_community_slug is null or p.community_slug=p_community_slug) and (p_cat_id is null or p.cat_id=p_cat_id) and (p_cursor is null or (p.created_at,p.id)<(v_created,v_id)) order by p.created_at desc,p.id desc limit least(greatest(coalesce(p_limit,20),1),50);
end $$;
create or replace function public.get_public_community_post(p_post_id uuid) returns table("postId" uuid,body text,"catId" uuid,"communitySlug" text,"createdAt" timestamptz,author jsonb,"replyCount" integer,"canDelete" boolean,cursor uuid) language sql stable security definer set search_path=pg_catalog as $$
 select p.id,p.body,p.cat_id,p.community_slug,p.created_at,jsonb_build_object('name',coalesce(profile.public_name,'Community member'),'avatarKey',coalesce(profile.avatar_key,'person')),(select count(*)::integer from public.community_replies r where r.post_id=p.id and r.parent_reply_id is null and private.community_reply_available(r.id,auth.uid())),coalesce(auth.uid() is not null and p.author_id=auth.uid(),false),p.id from public.community_posts p left join public.user_profiles profile on profile.id=p.author_id where p.id=p_post_id and private.community_post_available(p.id,auth.uid());
$$;

create or replace function private.lock_direct_lifecycle() returns void language plpgsql volatile security definer set search_path=pg_catalog as $$ begin perform pg_advisory_xact_lock(hashtextextended('direct_message_lifecycle',0)); end $$;
create or replace function private.lock_direct_block_pair() returns trigger language plpgsql security definer set search_path=pg_catalog as $$ begin perform private.lock_direct_lifecycle(); return new; end $$;
drop trigger if exists zzy_lock_direct_block_pair on public.user_blocks;
create trigger zzy_lock_direct_block_pair before insert on public.user_blocks for each row execute function private.lock_direct_block_pair();
create or replace function private.lock_direct_erasure_pairs() returns trigger language plpgsql security definer set search_path=pg_catalog as $$ begin perform private.lock_direct_lifecycle(); return new; end $$;
drop trigger if exists zzy_lock_direct_erasure_pairs on private.account_erasure_requests;
create trigger zzy_lock_direct_erasure_pairs before insert on private.account_erasure_requests for each row execute function private.lock_direct_erasure_pairs();
create or replace function private.purge_direct_messages_for_erasure() returns trigger language plpgsql security definer set search_path=pg_catalog as $$ begin delete from private.direct_conversations where member_low_id=old.id or member_high_id=old.id; return old; end $$;
create or replace function public.block_direct_conversation(p_conversation_id uuid,p_request_id uuid) returns uuid language plpgsql volatile security definer set search_path=pg_catalog as $$
declare v_actor uuid:=auth.uid(); v_target uuid; v_hash text; v_prior private.direct_message_requests%rowtype;
begin
 if v_actor is null then raise exception 'authentication_required' using errcode='42501'; end if; if p_conversation_id is null or p_request_id is null then raise exception 'invalid_direct_message_block' using errcode='22023'; end if;
 v_hash:=encode(extensions.digest(jsonb_build_object('conversationId',p_conversation_id)::text,'sha256'),'hex');
 perform pg_advisory_xact_lock(hashtextextended(v_actor::text||':'||p_request_id::text,0)); perform private.lock_direct_lifecycle(); perform pg_advisory_xact_lock(hashtextextended('direct_message_request:'||v_actor::text||':'||p_request_id::text,0));
 select * into v_prior from private.direct_message_requests where actor_id=v_actor and request_id=p_request_id for update; if found then if v_prior.operation<>'block' or v_prior.payload_hash<>v_hash then raise exception 'idempotency_conflict' using errcode='P0001'; end if; return p_request_id; end if;
 select case when member_low_id=v_actor then member_high_id else member_low_id end into v_target from private.direct_conversations where id=p_conversation_id and (member_low_id=v_actor or member_high_id=v_actor); if not found then raise exception 'direct_message_not_available' using errcode='P0001'; end if;
 perform public.block_user(v_target,p_request_id); insert into private.direct_message_requests(actor_id,request_id,operation,payload_hash,result_conversation_id) values(v_actor,p_request_id,'block',v_hash,p_conversation_id); return p_request_id;
end $$;
create or replace function public.request_account_erasure(p_request_id uuid) returns table("requestId" uuid,status text,"receivedAt" timestamptz) language plpgsql volatile security definer set search_path=pg_catalog as $$
declare v_actor_id uuid:=auth.uid(); request_row private.account_erasure_requests%rowtype;
begin
 if v_actor_id is null then raise exception 'authentication_required' using errcode='42501'; end if; if p_request_id is null then raise exception 'invalid_erasure_request' using errcode='22023'; end if;
 perform private.lock_direct_lifecycle(); perform pg_advisory_xact_lock(hashtextextended('account_erasure:'||v_actor_id::text,0)); perform 1 from auth.users user_row where user_row.id=v_actor_id for key share; if not found then raise exception 'authentication_required' using errcode='42501'; end if;
 select * into request_row from private.account_erasure_requests where target_subject_id=v_actor_id and request_id=p_request_id for update; if found then return query select request_row.request_id,request_row.status,request_row.created_at; return; end if; if exists(select 1 from private.account_erasure_requests e where e.target_subject_id=v_actor_id and e.status<>'completed') then raise exception 'erasure_already_pending' using errcode='P0001'; end if;
 insert into private.account_erasure_requests(request_id,subject_id,target_subject_id) values(p_request_id,v_actor_id,v_actor_id) returning * into request_row; insert into audit.access_audit(actor_id,action,resource_type,resource_id,purpose,request_id) values(case when exists(select 1 from public.user_profiles profile where profile.id=v_actor_id) then v_actor_id else null end,'request_account_erasure','account_erasure_request',request_row.id,'rights',p_request_id::text); return query select request_row.request_id,request_row.status,request_row.created_at;
end $$;

revoke all on function private.community_reply_available(uuid,uuid),private.community_target_available(text,uuid,uuid),private.can_read_profile_avatar(text,text,uuid),private.lock_direct_lifecycle(),private.lock_direct_block_pair(),private.lock_direct_erasure_pairs() from public,anon,authenticated,service_role;
revoke all on function public.get_community_author(text,uuid),public.create_direct_message_request(text,uuid,text,uuid),public.respond_direct_message_request(uuid,boolean,uuid),public.send_direct_message(uuid,text,uuid),public.mark_direct_conversation_read(uuid,uuid),public.list_my_direct_conversations(uuid,integer),public.list_public_community_replies(uuid,uuid,integer),public.list_my_community_activity(uuid,integer) from public,anon,authenticated,service_role;
grant execute on function public.get_community_author(text,uuid),public.list_public_community_replies(uuid,uuid,integer) to anon,authenticated;
-- Storage RLS evaluates this predicate as the reader; retain its policy execution grant.
grant execute on function private.can_read_profile_avatar(text,text,uuid) to anon,authenticated;
grant execute on function public.create_direct_message_request(text,uuid,text,uuid),public.respond_direct_message_request(uuid,boolean,uuid),public.send_direct_message(uuid,text,uuid),public.mark_direct_conversation_read(uuid,uuid),public.list_my_direct_conversations(uuid,integer),public.list_my_community_activity(uuid,integer) to authenticated;
commit;
